/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ActionOulineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M10.5063 4H13.5063V9.40312L18.1844 6.70312L19.6844 9.3L15.0063 12L19.6844 14.7L18.1844 17.2969L13.5063 14.5969V20H10.5063V14.5969L5.82812 17.2969L4.32812 14.7L9.00625 12L4.32812 9.3L5.82812 6.70312L10.5063 9.40312V4Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ActionOulineIcon
