/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ArrowDownOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M11.1616 3.24985L12.0091 2.40234L12.8566 3.24985L18.8566 9.24984L19.7041 10.0973L18.0054 11.7961C17.9566 11.7473 16.3554 10.1461 13.2054 6.99609V22.0973H10.8054V6.99609C7.65539 10.1461 6.05414 11.7473 6.00539 11.7961L4.30664 10.0973L5.15414 9.24984L11.1541 3.24985H11.1616Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ArrowDownOutlineIcon
