/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function Bell3FillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        opacity="0.4"
        d="M3 18H21L18 13.2V9.6C18 6.6975 15.9375 4.275 13.2 3.72V2.4H10.8V3.72C8.0625 4.275 6 6.6975 6 9.6V13.2L3 18Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
      <path
        id="Vector2"
        d="M9.67499 19.8C9.94124 20.835 10.8825 21.6 12 21.6C13.1175 21.6 14.0587 20.835 14.325 19.8H9.67499Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default Bell3FillIcon
