/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function BellNewFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Subtract"
        d="M14.3252 19.7988C14.0588 20.8337 13.1174 21.5986 12 21.5986C10.8826 21.5986 9.94117 20.8337 9.6748 19.7988H14.3252ZM13.2002 2.39844V3.71875C13.7188 3.82391 14.2131 3.99583 14.6738 4.22559C13.1166 4.77272 12 6.25576 12 8C12 10.2091 13.7909 12 16 12C16.7289 12 17.4115 11.8035 18 11.4629V13.1982L21 17.998H3L6 13.1982V9.59863C6 6.69622 8.06243 4.27385 10.7998 3.71875V2.39844H13.2002Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
      <circle id="Ellipse 203" cx="16" cy="8" r="4" fill="currentColor" />
    </svg>
  )
}

export default BellNewFillIcon
