/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function Bell2FillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        opacity="0.4"
        d="M3 18H21L18 13.2V9.6C18 6.6975 15.9375 4.275 13.2 3.72V2.4H10.8V3.72C8.0625 4.275 6 6.6975 6 9.6V13.2L3 18Z"
        fill="currentColor"
      />
      <path
        id="Vector2"
        d="M4.20002 9.6C4.20002 7.37625 5.13002 5.37375 6.62252 3.9525L5.37752 2.6475C3.54377 4.395 2.40002 6.86625 2.40002 9.6H4.20002ZM17.3775 3.9525C18.87 5.37375 19.8 7.37625 19.8 9.6H21.6C21.6 6.86625 20.4563 4.395 18.6225 2.6475L17.3775 3.9525ZM12 21.6C13.1175 21.6 14.0588 20.835 14.325 19.8H9.67502C9.94127 20.835 10.8825 21.6 12 21.6Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default Bell2FillIcon
