/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function BellOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12.9 2.4H11.1V3.66375C8.0475 4.09875 5.7 6.7275 5.7 9.9V12.6L3 18H21L18.3 12.6V9.9C18.3 6.7275 15.9525 4.09875 12.9 3.66375V2.4ZM18.0863 16.2H5.91L7.30875 13.4063C7.4325 13.155 7.5 12.8813 7.5 12.6V9.9C7.5 7.41375 9.51375 5.4 12 5.4C14.4863 5.4 16.5 7.41375 16.5 9.9V12.6C16.5 12.8813 16.5638 13.155 16.6913 13.4063L18.0863 16.2ZM9.45375 19.8C9.825 20.85 10.8263 21.6 12 21.6C13.1737 21.6 14.175 20.85 14.5463 19.8H9.45375Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default BellOutlineIcon
