/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function BookFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18 2.4H3.60001V21.6H20.4V19.2H19.2V16.8H20.4V2.4H18ZM7.20001 16.8H16.8V19.2H6.00001V18C6.00001 17.3363 6.53626 16.8 7.20001 16.8ZM8.40001 7.2H16.8V9H8.40001V7.2ZM16.8 10.8V12.6H8.40001V10.8H16.8Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default BookFillIcon
