/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function BullhornOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M16.665 4.82625L18.0638 3.6H20.4V20.4H18.0638L16.665 19.1738C15.03 17.745 12.9638 16.9125 10.8 16.8113V21.6H7.20002V16.8H2.40002V7.2H10.3688C12.6863 7.1925 14.9213 6.34875 16.665 4.82625ZM10.8 14.4V14.4075C13.4363 14.5088 15.9675 15.4763 18 17.16V6.83625C15.9675 8.52 13.4363 9.4875 10.8 9.58875V14.4Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default BullhornOutlineIcon
