/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CalendarFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M8.39999 3.6V2.4H5.99999V4.8H2.39999V20.4H10.56L10.905 18.3337L19.2037 10.035V4.79625H15.6037V2.39625H13.2037V4.79625H8.40374V3.59625L8.39999 3.6ZM5.99999 10.8H13.2V12.6H5.99999V10.8ZM10.8 16.2H5.99999V14.4H10.8V16.2ZM20.4 11.3962L18.42 13.3762L21.42 16.3762L23.4 14.3962L20.4 11.3962ZM12.6 19.1962L12 22.7962L15.6 22.1962L20.5725 17.2237L17.5725 14.2237L12.6 19.1962Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CalendarFillIcon
