/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ChatFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M1.2 1.2H15.6V13.8H9L4.8 16.8V13.8H1.2V1.2ZM8.4 19.8V16.44L9.5775 15.6H17.4V7.2H22.8V19.8H19.2V22.8L15 19.8H8.4Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ChatFillIcon
