/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CheckboxFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M20.4 20.4H3.60001V3.6H20.4V20.4ZM15.1688 8.0625L10.6913 14.22L8.10001 11.6287L6.82876 12.9L10.1625 16.2337L10.905 16.98L11.5238 16.1287L16.62 9.12L17.1488 8.3925L15.6938 7.33125L15.165 8.05875L15.1688 8.0625Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CheckboxFillIcon
