/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CheckboxOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18.6 5.4V18.6H5.40001V5.4H18.6ZM5.40001 3.6H3.60001V20.4H20.4V3.6H5.40001Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CheckboxOutlineIcon
