/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ChevronRightOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M16.1047 11.9994L15.2572 12.8469L9.25719 18.8469L8.40969 19.6944L6.71094 17.9956L12.7109 11.9956L7.55844 6.84313L6.71094 5.99562L8.40969 4.29688L9.25719 5.14437L15.2572 11.1444L16.1047 11.9919V11.9994Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ChevronRightOutlineIcon
