/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ChevronDownOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12.0113 17.2987L18.8588 10.4513L19.7063 9.60375L18.0075 7.905L17.16 8.7525L12.0075 13.905L6.85503 8.7525L6.00753 7.905L4.30878 9.60375L5.15628 10.4513L11.1563 16.4513L12.0038 17.2987H12.0113Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ChevronDownOutlineIcon
