/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ChevronUpOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12.0113 6.70125L12.8588 7.54875L19.7063 14.3962L18.0075 16.095L17.16 15.2475L12.0075 10.095L6.85503 15.2475L6.00753 16.095L4.30878 14.3962L5.15628 13.5487L11.1563 7.54875L12.0038 6.70125H12.0113Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ChevronUpOutlineIcon
