/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ChevronLeftOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M6.71094 11.9994L7.55844 12.8469L13.5584 18.8469L14.4059 19.6944L16.1047 17.9956L10.1047 11.9956L15.2572 6.84313L16.1047 5.99562L14.4059 4.29688L13.5584 5.14437L7.55844 11.1444L6.71094 11.9919V11.9994Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ChevronLeftOutlineIcon
