/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CircleCheckFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 21.6C6.69753 21.6 2.40002 17.3025 2.40002 12C2.40002 6.6975 6.69753 2.4 12 2.4C17.3025 2.4 21.6 6.6975 21.6 12C21.6 17.3025 17.3025 21.6 12 21.6ZM15.1688 8.0625L10.6913 14.22L8.10002 11.6288L6.82877 12.9L10.1625 16.2338L10.905 16.98L11.5238 16.1288L16.62 9.12L17.1488 8.3925L15.6938 7.33125L15.165 8.05875L15.1688 8.0625Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CircleCheckFillIcon
