/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CircleXmarkFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 21.6C17.3025 21.6 21.6 17.3025 21.6 12C21.6 6.6975 17.3025 2.4 12 2.4C6.69753 2.4 2.40002 6.6975 2.40002 12C2.40002 17.3025 6.69753 21.6 12 21.6ZM8.85378 13.8713L10.7288 12C9.27378 10.545 8.43752 9.70875 8.22002 9.49125L9.49127 8.22L12 10.7288C13.455 9.27375 14.2913 8.4375 14.5088 8.22L15.78 9.49125C15.5625 9.70875 14.7263 10.545 13.2713 12C14.7263 13.455 15.5625 14.2913 15.78 14.5088L14.5088 15.78C14.2913 15.5625 13.455 14.7263 12 13.2713C10.545 14.7263 9.70878 15.5625 9.49127 15.78L8.22002 14.5088L8.85752 13.8713H8.85378Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CircleXmarkFillIcon
