/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CircleXmarkOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 4.2C16.3088 4.2 19.8 7.69125 19.8 12C19.8 16.3088 16.3088 19.8 12 19.8C7.69127 19.8 4.20002 16.3088 4.20002 12C4.20002 7.69125 7.69127 4.2 12 4.2ZM12 21.6C17.3025 21.6 21.6 17.3025 21.6 12C21.6 6.6975 17.3025 2.4 12 2.4C6.69753 2.4 2.40002 6.6975 2.40002 12C2.40002 17.3025 6.69753 21.6 12 21.6ZM8.85378 13.8713L8.21627 14.5088L9.48752 15.78C9.70502 15.5625 10.5413 14.7263 11.9963 13.2713C13.4513 14.7263 14.2875 15.5625 14.505 15.78L15.7763 14.5088C15.5588 14.2913 14.7225 13.455 13.2675 12C14.7225 10.545 15.5588 9.70875 15.7763 9.49125L14.505 8.22C14.2875 8.4375 13.4513 9.27375 11.9963 10.7288L9.48752 8.22L8.21627 9.49125C8.43377 9.70875 9.27002 10.545 10.725 12L8.85378 13.8713Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CircleXmarkOutlineIcon
