/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CloseOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M6.85875 5.1525L6.01125 4.30125L4.3125 6L5.16 6.8475L10.3125 12L5.16 17.1525L4.3125 18L6.01125 19.6988L6.85875 18.8475L12.0113 13.6988L17.16 18.8475L18.0113 19.6988L19.7063 18L18.8588 17.1525L13.7063 12L18.8588 6.8475L19.7063 6L18.0113 4.30125L17.16 5.1525L12.0113 10.3013L6.85875 5.1525Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CloseOutlineIcon
