/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CompassFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M2.39999 12C2.39999 6.6975 6.69749 2.4 12 2.4C17.3025 2.4 21.6 6.6975 21.6 12C21.6 17.3025 17.3025 21.6 12 21.6C6.69749 21.6 2.39999 17.3025 2.39999 12ZM9.29999 9.3L7.19999 16.8L14.7 14.7L16.8 7.2L9.29999 9.3ZM12 10.8C12.6637 10.8 13.2 11.3363 13.2 12C13.2 12.6638 12.6637 13.2 12 13.2C11.3362 13.2 10.8 12.6638 10.8 12C10.8 11.3363 11.3362 10.8 12 10.8Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default CompassFillIcon
