/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function DartFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M21 3L1 10L8.80714 14.1321L13.7214 9.22143C14.0143 8.92857 14.4893 8.92857 14.7821 9.22143C15.075 9.51429 15.075 9.98929 14.7821 10.2821L9.86786 15.1929L14 23L21 3Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default DartFillIcon
