/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function DeleteOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M9.00001 1.8H15L15.6 3.6H20.4V6H3.60001V3.6H8.40001L9.00001 1.8ZM4.80001 7.8H19.2V21.6H4.80001V7.8ZM9.00001 10.2H7.20001V19.2H9.00001V10.2ZM12.9 10.2H11.1V19.2H12.9V10.2ZM16.8 10.2H15V19.2H16.8V10.2Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default DeleteOutlineIcon
