/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function EditOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M7.80002 12.6L7.20002 16.8L11.4 16.2L18.5625 9.0375L14.9625 5.4375L7.80002 12.6ZM22.2 5.4L18.6 1.8L16.2375 4.1625L19.8375 7.7625L22.2 5.4ZM3.60002 4.8H2.40002V21.6H19.2V13.2H16.8V19.2H4.80002V7.2H10.8V4.8H3.60002Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default EditOutlineIcon
