/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function EllipsisOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M14.0984 3.60156H9.89844V7.80156H14.0984V3.60156ZM9.89844 9.90156V14.1016H14.0984V9.90156H9.89844ZM9.89844 16.2016V20.4016H14.0984V16.2016H9.89844Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default EllipsisOutlineIcon
