/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ExportOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M8.41125 6H9.61125V3.6H2.41125V20.4H9.61125V18H4.81125V6H8.41125ZM21.2588 12.8475L22.1063 12L21.2588 11.1525L16.4588 6.3525L15.6113 5.505L13.9125 7.20375C14.16 7.45125 15.36 8.65125 17.5125 10.8037H8.41125V13.2037H17.5125L13.9125 16.8037L15.6113 18.5025L21.2588 12.855V12.8475Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ExportOutlineIcon
