/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function FileExportOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M9.01498 4.2H4.21498V19.8H15.015V17.4H16.815V21.6H2.41498V2.4H10.815L16.815 8.4V12H15.015V10.2H9.01498V4.2ZM15.015 15.6H10.815V13.8H19.7437C18.8812 12.9375 18.2812 12.3375 17.9437 12L19.215 10.7288C19.2937 10.8075 20.4075 11.9213 22.5525 14.0663L23.19 14.7038C23.1112 14.7825 21.9975 15.8963 19.8525 18.0413L19.215 18.6788L17.9437 17.4075C18.2812 17.07 18.8812 16.47 19.7437 15.6075H15.015V15.6ZM14.2725 8.4L10.8187 4.94625V8.4H14.2725Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default FileExportOutlineIcon
