/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function GamepadFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M22.8 7.20001V20.4H16.8L15.6 16.8H8.40001L7.20001 20.4H1.20001V7.20001L4.80001 3.60001H19.2L22.8 7.20001ZM6.30001 7.80001V9.90001H4.20001V11.7H6.30001V13.8H8.10001V11.7H10.2V9.90001H8.10001V7.80001H6.30001ZM16.2 11.4C15.5363 11.4 15 11.9363 15 12.6C15 13.2638 15.5363 13.8 16.2 13.8C16.8638 13.8 17.4 13.2638 17.4 12.6C17.4 11.9363 16.8638 11.4 16.2 11.4ZM18.6 7.80001C17.9363 7.80001 17.4 8.33626 17.4 9.00001C17.4 9.66376 17.9363 10.2 18.6 10.2C19.2638 10.2 19.8 9.66376 19.8 9.00001C19.8 8.33626 19.2638 7.80001 18.6 7.80001Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default GamepadFillIcon
