/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function GiftFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M14.4563 4.98C14.7413 4.49625 15.2588 4.2 15.8175 4.2H15.9C16.7288 4.2 17.4 4.87125 17.4 5.7C17.4 6.52875 16.7288 7.2 15.9 7.2H13.1513L14.4563 4.98ZM9.54377 4.98L10.8488 7.2H8.10002C7.27127 7.2 6.60002 6.52875 6.60002 5.7C6.60002 4.87125 7.27127 4.2 8.10002 4.2H8.18252C8.74127 4.2 9.26252 4.49625 9.54377 4.98ZM12.9038 4.06875L12 5.60625L11.0963 4.06875C10.4888 3.03375 9.37877 2.4 8.18252 2.4H8.10002C6.27752 2.4 4.80002 3.8775 4.80002 5.7C4.80002 6.24 4.93127 6.75 5.16002 7.2H2.40002V10.8H21.6V7.2H18.84C19.0688 6.75 19.2 6.24 19.2 5.7C19.2 3.8775 17.7225 2.4 15.9 2.4H15.8175C14.6213 2.4 13.5113 3.03375 12.9038 4.065V4.06875ZM20.4 12.6H12.9V20.4H20.4V12.6ZM11.1 12.6H3.60002V20.4H11.1V12.6Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default GiftFillIcon
