/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HeartFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M7.39124 3.6C8.99249 3.6 10.5 4.36875 11.4375 5.66625L12 6.4425L12.5625 5.66625C13.5 4.36875 15.0075 3.6 16.6087 3.6C19.365 3.6 21.6 5.835 21.6 8.59125C21.6 13.7212 15.8437 18.3487 12 21C8.15624 18.3487 2.39999 13.7212 2.39999 8.59125C2.39999 5.835 4.63499 3.6 7.39124 3.6Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default HeartFillIcon
