/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HeartOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 21C12 21 2.39999 14.3775 2.39999 8.68875C2.39999 5.9325 4.59749 3.6 7.39124 3.6C8.68874 3.6 9.91874 4.1025 10.8375 4.98C11.2912 5.41125 11.6362 5.94 12 6.44625C12.3637 5.94 12.7087 5.41125 13.1625 4.98C14.0812 4.1025 15.315 3.6 16.6087 3.6C19.4062 3.6 21.6 5.9325 21.6 8.68875C21.6 14.3775 12 21 12 21ZM12 9.5175L9.97874 6.72375C9.37874 5.895 8.41499 5.40375 7.39124 5.40375C5.62874 5.40375 4.19999 6.8325 4.19999 8.595C4.19999 9.84375 4.76249 11.0175 5.41874 12.0525C6.21749 13.3162 7.31624 14.5687 8.46374 15.6975C9.60374 16.8225 10.7512 17.7825 11.6137 18.465C11.7487 18.5737 11.88 18.6712 12 18.765C12.12 18.6712 12.2475 18.5737 12.3862 18.465C13.2525 17.7825 14.3962 16.8225 15.5362 15.6975C16.6837 14.5687 17.7787 13.3125 18.5812 12.0487C19.2375 11.0137 19.8037 9.84375 19.8037 8.59125C19.8037 6.82875 18.375 5.4 16.6125 5.4C15.5887 5.4 14.625 5.89125 14.025 6.72L12 9.5175Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default HeartOutlineIcon
