/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function LightbulbFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M15.6 15.8363C17.7525 14.5913 19.2 12.2663 19.2 9.6C19.2 5.625 15.975 2.4 12 2.4C8.02499 2.4 4.79999 5.625 4.79999 9.6C4.79999 12.2663 6.24749 14.5913 8.39999 15.8363V16.8H15.6V15.8363ZM15.6 18.6H8.39999V22.2H15.6V18.6ZM11.7 6.6C10.2075 6.6 8.99999 7.8075 8.99999 9.3V9.6H7.19999V9.3C7.19999 6.81375 9.21374 4.8 11.7 4.8H12V6.6H11.7Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default LightbulbFillIcon
