/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function LockFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M9.59999 6V8.4H14.4V6C14.4 4.67625 13.3237 3.6 12 3.6C10.6762 3.6 9.59999 4.67625 9.59999 6ZM7.19999 8.4V6C7.19999 3.34875 9.34874 1.2 12 1.2C14.6512 1.2 16.8 3.34875 16.8 6V8.4H19.2V21.6H4.79999V8.4H7.19999Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
      <path
        d="M10.6833 13.0286C11.1408 13.0286 11.5715 13.2482 11.8394 13.6189L12.0001 13.8407L12.1608 13.6189C12.4287 13.2482 12.8594 13.0286 13.3169 13.0286C14.1044 13.0286 14.7429 13.6671 14.7429 14.4546C14.7429 15.9204 13.0983 17.2425 12.0001 18C10.9019 17.2425 9.25723 15.9204 9.25723 14.4546C9.25723 13.6671 9.8958 13.0286 10.6833 13.0286Z"
        fill="currentColor"
      />
      <path
        d="M10.6833 13.0286C11.1408 13.0286 11.5715 13.2482 11.8394 13.6189L12.0001 13.8407L12.1608 13.6189C12.4287 13.2482 12.8594 13.0286 13.3169 13.0286C14.1044 13.0286 14.7429 13.6671 14.7429 14.4546C14.7429 15.9204 13.0983 17.2425 12.0001 18C10.9019 17.2425 9.25723 15.9204 9.25723 14.4546C9.25723 13.6671 9.8958 13.0286 10.6833 13.0286Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default LockFillIcon
