/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function LockFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Subtract"
        d="M12 1.2002C14.6512 1.2002 16.7998 3.34875 16.7998 6V8.40039H19.2002V21.5996H4.7998V8.40039H7.2002V6C7.2002 3.34875 9.34875 1.2002 12 1.2002ZM13.3164 13.0283C12.8591 13.0285 12.4289 13.2486 12.1611 13.6191L12 13.8408L11.8398 13.6191C11.572 13.2485 11.141 13.0284 10.6836 13.0283C9.89609 13.0283 9.25684 13.6676 9.25684 14.4551C9.25716 15.9206 10.9019 17.2426 12 18C13.0981 17.2426 14.7428 15.9206 14.7432 14.4551C14.7432 13.6676 14.1039 13.0283 13.3164 13.0283ZM12 3.59961C10.6762 3.59961 9.59961 4.67625 9.59961 6V8.40039H14.4004V6C14.4004 4.67625 13.3237 3.59962 12 3.59961Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default LockFillIcon
