/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function MessageSmileOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M2.4 3.6V19.2H7.2V22.8L13.2 19.2H21.6V3.6H2.4ZM9.6 8.4C10.2638 8.4 10.8 8.93625 10.8 9.6C10.8 10.2637 10.2638 10.8 9.6 10.8C8.93625 10.8 8.4 10.2637 8.4 9.6C8.4 8.93625 8.93625 8.4 9.6 8.4ZM14.4 8.4C15.0638 8.4 15.6 8.93625 15.6 9.6C15.6 10.2637 15.0638 10.8 14.4 10.8C13.7363 10.8 13.2 10.2637 13.2 9.6C13.2 8.93625 13.7363 8.4 14.4 8.4ZM8.6475 12.9C9.4725 13.8225 10.6688 14.4 12 14.4C13.3313 14.4 14.5275 13.8225 15.3525 12.9L16.695 14.1C15.5438 15.3862 13.8638 16.2 12 16.2C10.1363 16.2 8.45625 15.3862 7.305 14.1L8.6475 12.9Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default MessageSmileOutlineIcon
