/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function NavCommentFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M7 3H23V17L18.5 14V8.25C18.5 7.83571 18.1643 7.5 17.75 7.5H11.75C11.3357 7.5 11 7.83571 11 8.25C11 8.66429 11.3357 9 11.75 9H17V20H9.5L5 23V20H1V9H7V3Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default NavCommentFillIcon
