/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function NavHomeFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12.75 21H21V9L12 1L3 9V21H11.25V14.75C11.25 14.3357 11.5857 14 12 14C12.4143 14 12.75 14.3357 12.75 14.75V21Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default NavHomeFillIcon
