/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function NavMyFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 22C17.5214 22 22 17.5214 22 12C22 6.47857 17.5214 2 12 2C6.47857 2 2 6.47857 2 12C2 17.5214 6.47857 22 12 22ZM8.5 8C9.32857 8 10 8.67143 10 9.5C10 10.3286 9.32857 11 8.5 11C7.67143 11 7 10.3286 7 9.5C7 8.67143 7.67143 8 8.5 8ZM14 9.5C14 8.67143 14.6714 8 15.5 8C16.3286 8 17 8.67143 17 9.5C17 10.3286 16.3286 11 15.5 11C14.6714 11 14 10.3286 14 9.5ZM7.75 13H12.25C12.25 13 12.25 13.3357 12.25 13.75C12.25 14.1643 12.25 14.5 12.25 14.5H8.53571C8.77857 16.1964 10.2357 17.5 12 17.5C13.9321 17.5 15.5 15.9321 15.5 14V13.75C15.5 13.75 15.8357 13.75 16.25 13.75C16.6643 13.75 17 13.75 17 13.75V14C17 16.7607 14.7607 19 12 19C9.23929 19 7 16.7607 7 14V13.75C7 13.3357 7.33571 13 7.75 13Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default NavMyFillIcon
