/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function RecreateOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M21.6 9.6V2.1L18.6375 5.0625C14.8762 1.4625 8.90999 1.51125 5.21249 5.2125C3.32999 7.095 2.39249 9.56625 2.39999 12.0337C2.39999 12.1087 2.39999 12.18 2.40374 12.255C2.43749 13.5825 2.74124 14.8387 3.26249 15.9787C3.72749 16.9987 4.37624 17.9512 5.21249 18.7875C6.94874 20.5237 9.34874 21.6 12 21.6C15.7537 21.6 19.005 19.4437 20.58 16.3087L18.435 15.2287C17.25 17.5837 14.8125 19.1962 12 19.1962C8.83874 19.1962 6.14999 17.1562 5.18249 14.3212C4.95374 13.65 4.82624 12.9487 4.80374 12.2475C4.79999 12.165 4.79999 12.0787 4.79999 11.9925C4.79999 10.1475 5.50124 8.30625 6.90749 6.9C9.66749 4.14 14.115 4.0875 16.9387 6.75375L14.1 9.6H21.6Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default RecreateOutlineIcon
