/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SearchOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18.0113 10.2C18.0113 11.9213 17.4525 13.5113 16.5113 14.8013L21.2588 19.5525L22.1063 20.4L20.4113 22.0987L19.56 21.2475L14.8125 16.5C13.5225 17.445 11.9325 18 10.2113 18C5.9025 18 2.41125 14.5088 2.41125 10.2C2.41125 5.89125 5.9025 2.4 10.2113 2.4C14.52 2.4 18.0113 5.89125 18.0113 10.2ZM10.2113 15.6C13.1925 15.6 15.6113 13.1813 15.6113 10.2C15.6113 7.21875 13.1925 4.8 10.2113 4.8C7.23 4.8 4.81125 7.21875 4.81125 10.2C4.81125 13.1813 7.23 15.6 10.2113 15.6Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default SearchOutlineIcon
