/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SendFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M5.54999 10.9087L1.79999 1.8L24 12L1.79999 22.2L5.54999 13.0912L13.2 12L5.54999 10.9087Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default SendFillIcon
