/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SmileFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 21.6C17.3025 21.6 21.6 17.3025 21.6 12C21.6 6.6975 17.3025 2.4 12 2.4C6.69753 2.4 2.40002 6.6975 2.40002 12C2.40002 17.3025 6.69753 21.6 12 21.6ZM12 16.2C13.4325 16.2 14.7 15.4838 15.4575 14.3813L16.9388 15.405C15.8588 16.9725 14.0513 18 12 18C9.94877 18 8.14127 16.9725 7.05752 15.405L8.53877 14.3813C9.30002 15.4838 10.5675 16.2 12 16.2ZM7.80002 10.2C7.80002 9.53625 8.33627 9 9.00002 9C9.66377 9 10.2 9.53625 10.2 10.2C10.2 10.8638 9.66377 11.4 9.00002 11.4C8.33627 11.4 7.80002 10.8638 7.80002 10.2ZM15 9C15.6638 9 16.2 9.53625 16.2 10.2C16.2 10.8638 15.6638 11.4 15 11.4C14.3363 11.4 13.8 10.8638 13.8 10.2C13.8 9.53625 14.3363 9 15 9Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default SmileFillIcon
