/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ThumbsDownFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18.6 3.6V6H19.8V8.4H20.4V11.4H21V15.6H13.2L15 19.2L11.4 21L8.4 15.6V6L12 3.6H18.6ZM6.6 6V18H2.4V6H6.6Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ThumbsDownFillIcon
