/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ThumbsUpFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M8.39999 8.4L11.4 3L15 4.8L13.2 8.4H21V12.6H20.4V15.6H19.8V18H18.6V20.4H12L8.39999 18V8.4ZM6.59999 8.4V20.4H2.39999V8.4H6.59999Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ThumbsUpFillIcon
