/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ThumbsDownOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18.6 3.6V5.4H19.2V7.8H19.8V10.2H20.4V16.2H13.5525L15.4238 19.9425L14.6213 20.3438L10.8638 22.2225L10.0575 22.6237C9.8775 22.2675 9.43125 21.3712 8.715 19.9425L7.8 18.1087V18.6H2.4V6H6.70125L7.41 5.5575L9.81 4.0575L10.32 3.73875L10.5375 3.60375H18.5963L18.6 3.6ZM11.055 5.4L10.7625 5.58375L8.3625 7.08375L7.8 7.43625V14.085L10.3238 19.1362L10.86 20.2125L13.005 19.14C11.685 16.4962 10.8938 14.9175 10.6388 14.4037H18.5963V12.0037H17.9963V9.60375H17.3963V7.20375H16.7963V5.40375H11.0513L11.055 5.4ZM4.2 7.8V16.8H6V7.8H4.2Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ThumbsDownOutlineIcon
