/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ThumbsUpOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M10.8637 1.7775L14.6212 3.65625L15.4237 4.06125L13.5525 7.80375H20.4V13.8038H19.8V16.2038H19.2V18.6038H18.6V20.4037H10.5412L10.3237 20.2687L9.81375 19.95L7.80375 18.6938V20.4075H2.40375V7.8075H6.85125L8.7225 4.065C9.43875 2.6325 9.885 1.74 10.065 1.38375L10.8712 1.785L10.8637 1.7775ZM4.2 18.6H6V9.6H4.2V18.6ZM10.3275 4.86375L7.80375 9.91875V16.5675L8.36625 16.92L10.7662 18.42L11.0587 18.6038H16.8037V16.8038H17.4037V14.4038H18.0037V12.0038H18.6037V9.60375H10.6462C10.9012 9.09 11.6925 7.51125 13.0125 4.8675L10.8637 3.7875L10.3275 4.86375Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default ThumbsUpOutlineIcon
