/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function UnlockFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M18 3.6C16.6762 3.6 15.6 4.67625 15.6 6V8.4H19.2V21.6H4.79999V8.4H13.2V6C13.2 3.34875 15.3487 1.2 18 1.2C20.6512 1.2 22.8 3.34875 22.8 6V8.4H20.4V6C20.4 4.67625 19.3237 3.6 18 3.6ZM13.5 15.9H14.4V14.1H9.59999V15.9H13.5Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default UnlockFillIcon
