/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function VideoFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M16.8 4.8H2.39999V19.2H16.8V4.8ZM22.8 18V6L18.6 8.80125V15.2025L22.8 18.0038V18Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default VideoFillIcon
