/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function WandMagicFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M11 7.5L10.25 5.75L8.5 5L10.25 4.25L11 2.5L11.75 4.25L13.5 5L11.75 5.75L11 7.5ZM2.5 8L5 7L6 4.5L7 7L9.5 8L7 9L6 11.5L5 9L2.5 8ZM16.5 15.5L17.5 13L18.5 15.5L21 16.5L18.5 17.5L17.5 20L16.5 17.5L14 16.5L16.5 15.5ZM17.5 3.58438L20.4156 6.5L16.7375 10.1781L13.8219 7.2625L17.5 3.58438ZM3.58438 17.5L12.7625 8.32188L15.6781 11.2375L6.5 20.4156L3.58438 17.5Z"
        fill="currentColor"
        fillOpacity="0.9"
      />
    </svg>
  )
}

export default WandMagicFillIcon
