/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function AddCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <circle id="Ellipse 75" cx="12" cy="12" r="8.25" stroke={color} strokeWidth="1.5" />
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.25 16C11.25 16.4142 11.5858 16.75 12 16.75C12.4142 16.75 12.75 16.4142 12.75 16V12.7499H16C16.4142 12.7499 16.75 12.4142 16.75 11.9999C16.75 11.5857 16.4142 11.2499 16 11.2499H12.75V8C12.75 7.58579 12.4142 7.25 12 7.25C11.5858 7.25 11.25 7.58579 11.25 8V11.2499H8.00003C7.58582 11.2499 7.25003 11.5857 7.25003 11.9999C7.25003 12.4142 7.58582 12.7499 8.00003 12.7499H11.25V16Z"
        fill={color}
      />
    </svg>
  )
}

export default AddCircleOutlineIcon
