/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function AddCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M12 16.75C11.5858 16.75 11.25 16.4142 11.25 16V12.7499H8.00003C7.58582 12.7499 7.25003 12.4142 7.25003 11.9999C7.25003 11.5857 7.58582 11.2499 8.00003 11.2499H11.25V8C11.25 7.58579 11.5858 7.25 12 7.25C12.4142 7.25 12.75 7.58579 12.75 8V11.2499H16C16.4142 11.2499 16.75 11.5857 16.75 11.9999C16.75 12.4142 16.4142 12.7499 16 12.7499H12.75V16C12.75 16.4142 12.4142 16.75 12 16.75Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default AddCircleOutlineIcon
