/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function AddCircleFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Exclude"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM12 16.75C11.5858 16.75 11.25 16.4142 11.25 16V12.75H7.99998C7.58576 12.75 7.24998 12.4142 7.24998 12C7.24998 11.5858 7.58576 11.25 7.99998 11.25H11.25V7.99998C11.25 7.58576 11.5858 7.24998 12 7.24998C12.4142 7.24998 12.75 7.58576 12.75 7.99998V11.25H16C16.4142 11.25 16.75 11.5858 16.75 12C16.75 12.4142 16.4142 12.75 16 12.75H12.75V16C12.75 16.4142 12.4142 16.75 12 16.75Z"
        fill={color}
      />
    </svg>
  )
}

export default AddCircleFillIcon
