/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function AiCircleFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Subtract"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM10.7916 8.625H10.0305L7.5 15.375H8.83443L9.42906 13.6302H12.0701L12.6647 15.375H13.9992L11.4638 8.625H11.0881H10.7916ZM10.7916 9.87864H10.7076L9.7463 12.6993H11.7529L10.7916 9.87864ZM16.5 8.625H15.2249V15.375H16.5V8.625Z"
        fill={color}
      />
    </svg>
  )
}

export default AiCircleFillIcon
