/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ApplyOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.8082 6.58896C18.1334 6.14262 18.0353 5.51711 17.589 5.19184C17.1426 4.86657 16.5171 4.96472 16.1918 5.41106L11.0361 12.4859L7.69224 9.27835C7.29368 8.89603 6.66065 8.9092 6.27834 9.30776C5.89602 9.70633 5.90919 10.3394 6.30776 10.7217L10.4778 14.7217C10.6861 14.9215 10.9706 15.0216 11.2581 14.9961C11.5456 14.9707 11.8082 14.8222 11.9782 14.589L17.8082 6.58896ZM5 17C4.44772 17 4 17.4477 4 18C4 18.5523 4.44772 19 5 19H19C19.5523 19 20 18.5523 20 18C20 17.4477 19.5523 17 19 17H5Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ApplyOutlineIcon
