/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ArrowDownOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        d="M12.2871 18.1931C12.3755 18.1565 12.4584 18.1022 12.5303 18.0303L17.5303 13.0303C17.8232 12.7374 17.8232 12.2626 17.5303 11.9697C17.2374 11.6768 16.7626 11.6768 16.4697 11.9697L12.75 15.6893L12.75 6.5C12.75 6.08579 12.4142 5.75 12 5.75C11.5858 5.75 11.25 6.08579 11.25 6.5L11.25 15.6893L7.53033 11.9697C7.23744 11.6768 6.76256 11.6768 6.46967 11.9697C6.17678 12.2626 6.17678 12.7374 6.46967 13.0303L11.4697 18.0303C11.6161 18.1768 11.8081 18.25 12 18.25C12.1017 18.25 12.1987 18.2298 12.2871 18.1931Z"
        fill={color}
      />
    </svg>
  )
}

export default ArrowDownOutlineIcon
