/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ArrowLeftOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        d="M5.80691 12.2871C5.84351 12.3755 5.89776 12.4584 5.96967 12.5303L10.9697 17.5303C11.2626 17.8232 11.7374 17.8232 12.0303 17.5303C12.3232 17.2374 12.3232 16.7626 12.0303 16.4697L8.31066 12.75L17.5 12.75C17.9142 12.75 18.25 12.4142 18.25 12C18.25 11.5858 17.9142 11.25 17.5 11.25L8.31066 11.25L12.0303 7.53033C12.3232 7.23744 12.3232 6.76256 12.0303 6.46967C11.7374 6.17678 11.2626 6.17678 10.9697 6.46967L5.96967 11.4697C5.82322 11.6161 5.75 11.8081 5.75 12C5.75 12.1017 5.77024 12.1987 5.80691 12.2871Z"
        fill={color}
      />
    </svg>
  )
}

export default ArrowLeftOutlineIcon
