/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ArrowUpOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.7129 5.80691C11.6245 5.84351 11.5416 5.89776 11.4697 5.96967L6.46967 10.9697C6.17678 11.2626 6.17678 11.7374 6.46967 12.0303C6.76256 12.3232 7.23744 12.3232 7.53033 12.0303L11.25 8.31066V17.5C11.25 17.9142 11.5858 18.25 12 18.25C12.4142 18.25 12.75 17.9142 12.75 17.5V8.31066L16.4697 12.0303C16.7626 12.3232 17.2374 12.3232 17.5303 12.0303C17.8232 11.7374 17.8232 11.2626 17.5303 10.9697L12.5303 5.96967C12.3839 5.82322 12.1919 5.75 12 5.75C11.8983 5.75 11.8013 5.77024 11.7129 5.80691Z"
        fill={color}
      />
    </svg>
  )
}

export default ArrowUpOutlineIcon
