/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ArrowRightOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        d="M18.1931 11.7129C18.1565 11.6245 18.1022 11.5416 18.0303 11.4697L13.0303 6.46967C12.7374 6.17678 12.2626 6.17678 11.9697 6.46967C11.6768 6.76256 11.6768 7.23744 11.9697 7.53033L15.6893 11.25L6.5 11.25C6.08579 11.25 5.75 11.5858 5.75 12C5.75 12.4142 6.08579 12.75 6.5 12.75L15.6893 12.75L11.9697 16.4697C11.6768 16.7626 11.6768 17.2374 11.9697 17.5303C12.2626 17.8232 12.7374 17.8232 13.0303 17.5303L18.0303 12.5303C18.1768 12.3839 18.25 12.1919 18.25 12C18.25 11.8983 18.2298 11.8013 18.1931 11.7129Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ArrowRightOutlineIcon
