/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function AssetStoreOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.99999 6.99812C9.99999 5.89204 10.8917 5 12 5C13.1083 5 14 5.89204 14 6.99812V7H9.99999V6.99812ZM7.99999 7V6.99812C7.99999 4.78629 9.7883 3 12 3C14.2117 3 16 4.78629 16 6.99812V7H17.4372C18.365 7 19.254 7.68148 19.3251 8.70033L19.3255 8.70574L19.3255 8.70574L19.9828 18.9205C20.1495 20.0923 19.1757 21 18.1074 21H18.0974H5.89254C4.82433 21 3.85052 20.0923 4.01717 18.9205L4.67451 8.70574L4.67476 8.70191L4.67477 8.70191C4.74562 7.66316 5.64443 7 6.56281 7H7.99999ZM15 9H8.99999H6.65971L6.01619 19H17.9838L17.3403 9H15Z"
        fill={color}
      />
    </svg>
  )
}

export default AssetStoreOutlineIcon
