/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function AssetStoreOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.99999 7V6.99812C7.99999 4.78629 9.7883 3 12 3C14.2117 3 16 4.78629 16 6.99812V7H17.4372C18.365 7 19.254 7.68148 19.3251 8.70033L19.3255 8.70574L19.9828 18.9205C20.1495 20.0923 19.1757 21 18.1074 21H5.89254C4.82433 21 3.85052 20.0923 4.01717 18.9205L4.67476 8.70191C4.74562 7.66316 5.64443 7 6.56281 7H7.99999ZM9.99999 6.99812C9.99999 5.89204 10.8917 5 12 5C13.1083 5 14 5.89204 14 6.99812V7H9.99999V6.99812ZM6.65971 9L6.01619 19H17.9838L17.3403 9H6.65971Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default AssetStoreOutlineIcon
