/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function AssetStoreFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10 6.99812C10 5.89204 10.8917 5 12 5C13.1083 5 14 5.89204 14 6.99812V7H10V6.99812ZM8.00001 7V6.99812C8.00001 4.78629 9.78831 3 12 3C14.2117 3 16 4.78629 16 6.99812V7H17.4372C18.365 7 19.254 7.68148 19.3251 8.70033L19.3255 8.70574L19.3255 8.70574L19.9828 18.9205C20.1495 20.0923 19.1757 21 18.1075 21H18.0975H5.89255C4.82435 21 3.85053 20.0923 4.01718 18.9205L4.67453 8.70574L4.67478 8.70191L4.67478 8.70191C4.74564 7.66316 5.64444 7 6.56282 7H8.00001Z"
        fill={color}
      />
    </svg>
  )
}

export default AssetStoreFillIcon
