/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function BackgroundOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6 4C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4H6ZM6 6H18V18H6V6ZM16.54 17H7.42004L7.43004 16.99C7.05004 16.99 6.83004 16.59 7.06004 16.31L8.87004 14.06C9.06004 13.82 9.44004 13.83 9.62004 14.08L10.73 15.64C10.91 15.89 11.29 15.9 11.48 15.66L13.48 13.17C13.66 12.95 14.01 12.94 14.2 13.16L16.9 16.31C17.14 16.59 16.92 17 16.54 17Z"
        fill={color}
      />
    </svg>
  )
}

export default BackgroundOutlineIcon
