/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CallAcceptOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M4.2592 4.27369L5.27153 3.26138C5.62004 2.91287 6.20088 2.91287 6.56598 3.26138L9.65276 6.34812C10.0013 6.69662 10.0013 7.27746 9.65276 7.64256L8.12597 9.16933C7.76087 9.53443 7.6447 10.0655 7.82725 10.5467L7.86044 10.6131C8.80639 13.1688 10.8311 15.1934 13.3868 16.1394L13.4532 16.1726C13.9344 16.3551 14.4655 16.239 14.8306 15.8739L16.3574 14.3471C16.7059 13.9986 17.2867 13.9986 17.6518 14.3471L20.7386 17.4338C21.0871 17.7823 21.0871 18.3632 20.7386 18.7283L19.7263 19.7406C19.2948 20.1721 18.7803 20.504 18.1995 20.7197C16.2246 21.4167 12.6732 21.118 7.77746 16.239C2.88176 11.3599 2.58304 7.79191 3.28006 5.80047C3.47921 5.21963 3.82771 4.70517 4.2592 4.27369Z"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeMiterlimit="10"
      />
    </svg>
  )
}

export default CallAcceptOutlineIcon
