/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function CameraOnOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.29289 4.29289C9.48043 4.10536 9.73478 4 10 4H14C14.2652 4 14.5196 4.10536 14.7071 4.29289L16.4142 6H19C20.1023 6 21 6.89772 21 8V18C21 19.1023 20.1023 20 19 20H5C3.89772 20 3 19.1023 3 18V8C3 6.89772 3.89772 6 5 6H7.58579L9.29289 4.29289ZM10.4142 6L8.70711 7.70711C8.51957 7.89464 8.26522 8 8 8H5V18H19V8H16C15.7348 8 15.4804 7.89464 15.2929 7.70711L13.5858 6H10.4142Z"
        fill={color}
      />
      <path
        id="Vector (Stroke)2"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 10.75C10.7574 10.75 9.75 11.7574 9.75 13C9.75 14.2426 10.7574 15.25 12 15.25C13.2426 15.25 14.25 14.2426 14.25 13C14.25 11.7574 13.2426 10.75 12 10.75ZM8.25 13C8.25 10.9289 9.92893 9.25 12 9.25C14.0711 9.25 15.75 10.9289 15.75 13C15.75 15.0711 14.0711 16.75 12 16.75C9.92893 16.75 8.25 15.0711 8.25 13Z"
        fill={color}
      />
    </svg>
  )
}

export default CameraOnOutlineIcon
