/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CameraOnOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.96967 3.21967C7.11032 3.07902 7.30109 3 7.5 3H10.5C10.6989 3 10.8897 3.07902 11.0303 3.21967L12.3107 4.5H14.25C15.0767 4.5 15.75 5.17329 15.75 6V13.5C15.75 14.3267 15.0767 15 14.25 15H3.75C2.92329 15 2.25 14.3267 2.25 13.5V6C2.25 5.17329 2.92329 4.5 3.75 4.5H5.68934L6.96967 3.21967ZM7.81066 4.5L6.53033 5.78033C6.38968 5.92098 6.19891 6 6 6H3.75V13.5H14.25V6H12C11.8011 6 11.6103 5.92098 11.4697 5.78033L10.1893 4.5H7.81066Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9 8.0625C8.06802 8.0625 7.3125 8.81802 7.3125 9.75C7.3125 10.682 8.06802 11.4375 9 11.4375C9.93198 11.4375 10.6875 10.682 10.6875 9.75C10.6875 8.81802 9.93198 8.0625 9 8.0625ZM6.1875 9.75C6.1875 8.1967 7.4467 6.9375 9 6.9375C10.5533 6.9375 11.8125 8.1967 11.8125 9.75C11.8125 11.3033 10.5533 12.5625 9 12.5625C7.4467 12.5625 6.1875 11.3033 6.1875 9.75Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CameraOnOutlineIcon
