/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ChatFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Ellipse 62 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.11491 5.54888C6.90512 4.22451 9.34195 3.42847 12 3.42847C14.658 3.42847 17.0948 4.22451 18.885 5.54888C20.6754 6.8734 21.8571 8.76308 21.8571 10.9165C21.8571 13.07 20.6754 14.9596 18.885 16.2842C17.1664 17.5556 14.8518 18.3401 12.3177 18.4008C11.0685 19.5283 8.75189 20.9859 4.95595 20.4613C4.63086 20.4164 4.36794 20.1772 4.29585 19.8607C4.22377 19.5443 4.35759 19.2168 4.63184 19.0386C4.89431 18.868 5.3711 18.3623 5.5601 17.7759C5.64884 17.5006 5.66382 17.24 5.59485 16.998C5.52748 16.7617 5.36124 16.4763 4.97099 16.1755C3.26167 14.8578 2.14282 13.0114 2.14282 10.9165C2.14282 8.76308 3.32452 6.8734 5.11491 5.54888Z"
        fill={color}
      />
    </svg>
  )
}

export default ChatFillIcon
