/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CheckCircleFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Exclude"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM15.9394 10.2439C16.2122 9.93215 16.1806 9.45833 15.8689 9.18557C15.5572 8.91281 15.0833 8.94439 14.8106 9.25612L11.3903 13.165L9.1444 11.009C8.84559 10.7221 8.37082 10.7318 8.08396 11.0306C7.7971 11.3294 7.80679 11.8042 8.1056 12.091L10.9181 14.791C11.0659 14.933 11.2654 15.0082 11.4701 14.9993C11.6748 14.9904 11.867 14.8981 12.0019 14.7439L15.9394 10.2439Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CheckCircleFillIcon
