/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function CheckCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <circle id="Ellipse 75" cx="12" cy="12" r="8.25" stroke={color} strokeWidth="1.5" />
      <path
        id="Vector 1"
        d="M9 11.6L11.5 14L15 10"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default CheckCircleOutlineIcon
