/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CheckCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M15.5644 10.4939C15.8372 10.1822 15.8056 9.70833 15.4939 9.43557C15.1822 9.16281 14.7083 9.19439 14.4356 9.50612L11.4528 12.915L9.5194 11.059C9.22059 10.7721 8.74582 10.7818 8.45896 11.0806C8.1721 11.3794 8.18179 11.8542 8.4806 12.141L10.9806 14.541C11.1284 14.683 11.3279 14.7582 11.5326 14.7493C11.7373 14.7404 11.9295 14.6481 12.0644 14.4939L15.5644 10.4939Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CheckCircleOutlineIcon
