/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CheckOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 1 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M20.6139 5.21063C21.0499 5.5497 21.1284 6.17798 20.7893 6.61393L11.456 18.6139C11.2758 18.8456 11.0029 18.9865 10.7096 18.9991C10.4163 19.0117 10.1323 18.8948 9.9329 18.6794L3.26624 11.4794C2.89101 11.0741 2.91534 10.4415 3.32059 10.0662C3.72583 9.691 4.35853 9.71533 4.73376 10.1206L10.6003 16.4565L19.2106 5.38604C19.5497 4.9501 20.178 4.87156 20.6139 5.21063Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CheckOutlineIcon
