/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ClipCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12ZM21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM13.654 7.69873L10.8502 10.3409C10.423 10.7435 10.1232 11.2627 9.98818 11.834L9.10186 15.5832C8.93068 16.3073 9.80463 16.8119 10.3461 16.3016L13.1498 13.6594C13.5771 13.2568 13.8768 12.7376 14.0119 12.1663L14.8982 8.4171C15.0694 7.69303 14.1954 7.18846 13.654 7.69873Z"
        fill={color}
      />
    </svg>
  )
}

export default ClipCircleOutlineIcon
