/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ClipCircleFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="explore"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM13.6559 7.69523L10.8493 10.3402C10.422 10.7428 10.1223 11.2619 9.98723 11.8333L9.09998 15.5864C8.92881 16.3104 9.80276 16.815 10.3442 16.3047L13.1509 13.6598C13.5781 13.2572 13.8779 12.738 14.0129 12.1667L14.9002 8.4136C15.0714 7.68953 14.1974 7.18496 13.6559 7.69523Z"
        fill={color}
      />
    </svg>
  )
}

export default ClipCircleFillIcon
