/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function Close_CircleFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Exclude"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM8.43431 8.43398C8.74673 8.12156 9.25326 8.12156 9.56568 8.43398L12.0003 10.8686L14.4343 8.43455C14.7467 8.12213 15.2533 8.12213 15.5657 8.43455C15.8781 8.74697 15.8781 9.2535 15.5657 9.56592L13.1316 12L15.5657 14.434C15.8781 14.7464 15.8781 15.2529 15.5657 15.5653C15.2533 15.8778 14.7467 15.8778 14.4343 15.5653L12.0003 13.1313L9.56568 15.5659C9.25326 15.8783 8.74673 15.8783 8.43431 15.5659C8.12189 15.2535 8.12189 14.747 8.43431 14.4346L10.8689 12L8.43431 9.56535C8.12189 9.25293 8.12189 8.7464 8.43431 8.43398Z"
        fill={color}
      />
    </svg>
  )
}

export default Close_CircleFillIcon
