/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function CloseCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <circle id="Ellipse 76" cx="12" cy="12" r="8.25" stroke={color} strokeWidth="1.5" />
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M15.5657 9.5657C15.8781 9.25328 15.8781 8.74675 15.5657 8.43433C15.2533 8.12191 14.7467 8.12191 14.4343 8.43433L12 10.8686L9.5657 8.43434C9.25328 8.12192 8.74675 8.12192 8.43433 8.43434C8.12191 8.74676 8.12191 9.25329 8.43433 9.56571L10.8686 12L8.43432 14.4343C8.1219 14.7467 8.1219 15.2533 8.43432 15.5657C8.74674 15.8781 9.25327 15.8781 9.56569 15.5657L12 13.1314L14.4343 15.5657C14.7468 15.8781 15.2533 15.8781 15.5657 15.5657C15.8781 15.2533 15.8781 14.7468 15.5657 14.4343L13.1314 12L15.5657 9.5657Z"
        fill={color}
      />
    </svg>
  )
}

export default CloseCircleOutlineIcon
