/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function CloseCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M15.5657 8.43433C15.8781 8.74675 15.8781 9.25328 15.5657 9.5657L13.1314 12L15.5657 14.4343C15.8781 14.7468 15.8781 15.2533 15.5657 15.5657C15.2533 15.8781 14.7468 15.8781 14.4343 15.5657L12 13.1314L9.56569 15.5657C9.25327 15.8781 8.74674 15.8781 8.43432 15.5657C8.1219 15.2533 8.1219 14.7467 8.43432 14.4343L10.8686 12L8.43433 9.56571C8.12191 9.25329 8.12191 8.74676 8.43433 8.43434C8.74675 8.12192 9.25328 8.12192 9.5657 8.43434L12 10.8686L14.4343 8.43433C14.7467 8.12191 15.2533 8.12191 15.5657 8.43433Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default CloseCircleOutlineIcon
