/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function DangerOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M12 19C12.6904 19 13.25 18.4404 13.25 17.75C13.25 17.0596 12.6904 16.5 12 16.5C11.3096 16.5 10.75 17.0596 10.75 17.75C10.75 18.4404 11.3096 19 12 19Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 5C12.5523 5 13 5.44772 13 6L13 14C13 14.5523 12.5523 15 12 15C11.4477 15 11 14.5523 11 14L11 6C11 5.44772 11.4477 5 12 5Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default DangerOutlineIcon
