/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function DirectionCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12ZM21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM12.5628 7.875C12.5628 7.56434 12.3109 7.3125 12.0003 7.3125C11.6896 7.3125 11.4378 7.56434 11.4378 7.875V11.0259L8.70883 9.45036C8.4398 9.29503 8.09577 9.38721 7.94044 9.65625C7.78511 9.92529 7.8773 10.2693 8.14633 10.4246L10.8749 12L8.14633 13.5754C7.8773 13.7307 7.78511 14.0747 7.94044 14.3438C8.09577 14.6128 8.4398 14.705 8.70883 14.5496L11.4378 12.9741V16.125C11.4378 16.4357 11.6896 16.6875 12.0003 16.6875C12.3109 16.6875 12.5628 16.4357 12.5628 16.125V12.9745L15.291 14.5496C15.5601 14.705 15.9041 14.6128 16.0594 14.3438C16.2148 14.0747 16.1226 13.7307 15.8535 13.5754L13.1249 12L15.8535 10.4246C16.1226 10.2693 16.2148 9.92529 16.0594 9.65625C15.9041 9.38721 15.5601 9.29503 15.291 9.45036L12.5628 11.0255V7.875Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default DirectionCircleOutlineIcon
