/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function DirectionCircleFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Exclude"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM12.6332 7.35938C12.6332 7.00988 12.3499 6.72656 12.0004 6.72656C11.6509 6.72656 11.3676 7.00988 11.3676 7.35938V10.9042L8.29751 9.13166C7.99484 8.95691 7.60782 9.06061 7.43307 9.36328C7.25832 9.66595 7.36203 10.053 7.66469 10.2277L10.7344 12L7.66469 13.7723C7.36203 13.947 7.25832 14.334 7.43307 14.6367C7.60782 14.9394 7.99484 15.0431 8.29751 14.8683L11.3676 13.0958V16.6406C11.3676 16.9901 11.6509 17.2734 12.0004 17.2734C12.3499 17.2734 12.6332 16.9901 12.6332 16.6406V13.0963L15.7025 14.8683C16.0052 15.0431 16.3922 14.9394 16.5669 14.6367C16.7417 14.334 16.638 13.947 16.3353 13.7723L13.2656 12L16.3353 10.2277C16.638 10.053 16.7417 9.66595 16.5669 9.36328C16.3922 9.06061 16.0052 8.95691 15.7025 9.13166L12.6332 10.9037V7.35938Z"
        fill={color}
      />
    </svg>
  )
}

export default DirectionCircleFillIcon
