/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function DirectionCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Exclude"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.0003 7.3125C12.3109 7.3125 12.5628 7.56434 12.5628 7.875V11.0255L15.291 9.45036C15.5601 9.29503 15.9041 9.38721 16.0594 9.65625C16.2148 9.92529 16.1226 10.2693 15.8535 10.4246L13.1249 12L15.8535 13.5754C16.1226 13.7307 16.2148 14.0747 16.0594 14.3438C15.9041 14.6128 15.5601 14.705 15.291 14.5496L12.5628 12.9745V16.125C12.5628 16.4357 12.3109 16.6875 12.0003 16.6875C11.6896 16.6875 11.4378 16.4357 11.4378 16.125V12.9741L8.70883 14.5496C8.4398 14.705 8.09577 14.6128 7.94044 14.3437C7.78511 14.0747 7.8773 13.7307 8.14633 13.5754L10.8749 12L8.14633 10.4246C7.8773 10.2693 7.78511 9.92529 7.94044 9.65625C8.09577 9.38721 8.4398 9.29503 8.70883 9.45036L11.4378 11.0259V7.875C11.4378 7.56434 11.6896 7.3125 12.0003 7.3125Z"
        fill={color}
      />
      <circle id="Ellipse 75" cx="12" cy="12" r="8.25" stroke={color} strokeWidth="1.5" />
    </svg>
  )
}

export default DirectionCircleOutlineIcon
