/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function DownloadOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 5C12.5523 5 13 5.44772 13 6V11.5858L15.2929 9.29289C15.6834 8.90237 16.3166 8.90237 16.7071 9.29289C17.0976 9.68342 17.0976 10.3166 16.7071 10.7071L12.7071 14.7071C12.3166 15.0976 11.6834 15.0976 11.2929 14.7071L7.29289 10.7071C6.90237 10.3166 6.90237 9.68342 7.29289 9.29289C7.68342 8.90237 8.31658 8.90237 8.70711 9.29289L11 11.5858V6C11 5.44772 11.4477 5 12 5ZM6 16.01C6 15.4577 5.55228 15.01 5 15.01C4.44772 15.01 4 15.4577 4 16.01V18C4 18.9846 4.72816 20.01 5.88 20.01H18.12C19.2887 20.01 20 18.9768 20 18V16.01C20 15.4577 19.5523 15.01 19 15.01C18.4477 15.01 18 15.4577 18 16.01V18L17.9998 18.01H6.00029C6.0001 18.0068 6 18.0035 6 18V16.01Z"
        fill={color}
      />
    </svg>
  )
}

export default DownloadOutlineIcon
