/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function DuplicateOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6 6V15H15V6H6ZM4 5.96661C4 4.88048 4.88048 4 5.96661 4H15.0334C16.1195 4 17 4.88048 17 5.96661V15.0334C17 16.1195 16.1195 17 15.0334 17H5.96661C4.88048 17 4 16.1195 4 15.0334V5.96661ZM11.25 8.5C11.25 8.08579 10.9142 7.75 10.5 7.75C10.0858 7.75 9.75 8.08579 9.75 8.5V9.75H8.5C8.08579 9.75 7.75 10.0858 7.75 10.5C7.75 10.9142 8.08579 11.25 8.5 11.25H9.75V12.5C9.75 12.9142 10.0858 13.25 10.5 13.25C10.9142 13.25 11.25 12.9142 11.25 12.5V11.25H12.5C12.9142 11.25 13.25 10.9142 13.25 10.5C13.25 10.0858 12.9142 9.75 12.5 9.75H11.25V8.5ZM20 8.5C20 7.94772 19.5523 7.5 19 7.5C18.4477 7.5 18 7.94772 18 8.5V18.01H8.48999C7.93771 18.01 7.48999 18.4577 7.48999 19.01C7.48999 19.5623 7.93771 20.01 8.48999 20.01H18.12C19.1697 20.01 20 19.1549 20 18.13V8.5Z"
        fill={color}
      />
    </svg>
  )
}

export default DuplicateOutlineIcon
