/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function EditOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.9307 5.41401C15.7117 4.63305 16.9779 4.63305 17.7589 5.41401L18.5856 6.24056C19.3667 7.02163 19.3667 8.28806 18.5856 9.06913L16.9579 10.6967L13.3027 7.04182L14.9307 5.41401ZM16.3448 6.40545L15.7084 7.04182L16.9579 8.29121L17.5943 7.65485L16.3448 6.40545ZM12.6676 7.67792L16.3228 11.3328L7.65539 19.9993L4.00119 20L4 16.3446L12.6676 7.67792ZM5.7013 17.0489L5.70171 18.2988L6.95064 18.2985L13.9171 11.3328L12.6676 10.0834L5.7013 17.0489Z"
        fill={color}
      />
    </svg>
  )
}

export default EditOutlineIcon
