/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function FavoriteOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="star"
        d="M11.7227 4.33582C11.8136 4.12142 12.0913 4.09462 12.2285 4.25574L12.2773 4.33582L14.2529 9.00964L14.4287 9.42566L14.8789 9.46472L19.9736 9.9071C20.2055 9.92742 20.3167 10.1829 20.2061 10.3632L20.1445 10.4344L16.292 13.7753L15.9502 14.0712L16.0527 14.5106L17.2012 19.4755C17.2536 19.7024 17.0445 19.8873 16.8389 19.8378L16.752 19.8016L12.3877 17.1688L12 16.9344L11.6123 17.1688L7.24805 19.8016C7.04856 19.9217 6.80847 19.7802 6.79199 19.5692L6.79883 19.4755L7.94727 14.5106L8.0498 14.0712L7.70801 13.7753L3.85547 10.4344C3.67975 10.282 3.73955 10.0108 3.93457 9.92957L4.02637 9.9071L9.12109 9.46472L9.57129 9.42566L9.74707 9.00964L11.7227 4.33582Z"
        stroke="currentColor"
        strokeWidth="1.5"
      />
    </svg>
  )
}

export default FavoriteOutlineIcon
