/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function FavoriteOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="star"
        d="M7.41612 14.7709L7.51788 14.331L7.17671 14.0352L2.89581 10.3238C2.61675 10.0818 2.76555 9.62337 3.1335 9.59143L8.79435 9.10004L9.24444 9.06097L9.42032 8.64483L11.6149 3.4522C11.7588 3.1118 12.2412 3.1118 12.3851 3.4522L14.5797 8.64483L14.7556 9.06097L15.2057 9.10004L20.8665 9.59143C21.2344 9.62337 21.3833 10.0818 21.1042 10.3238L16.8233 14.0352L16.4821 14.331L16.5839 14.7709L17.8599 20.2873C17.9432 20.6472 17.553 20.9303 17.2367 20.7395L12.3874 17.8142L12 17.5805L11.6126 17.8142L6.76329 20.7395C6.44702 20.9303 6.05683 20.6472 6.14007 20.2873L7.41612 14.7709Z"
        stroke={color}
        strokeWidth="1.5"
      />
    </svg>
  )
}

export default FavoriteOutlineIcon
