/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function FavoriteOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="star"
        d="M11.7227 4.33582C11.8265 4.09101 12.1735 4.09101 12.2773 4.33582L14.2529 9.00964L14.4287 9.42566L14.8789 9.46472L19.9736 9.9071C20.2385 9.93032 20.3454 10.2601 20.1445 10.4344L16.292 13.7753L15.9502 14.0712L16.0527 14.5106L17.2012 19.4755C17.2611 19.7347 16.9798 19.9388 16.752 19.8016L12.3877 17.1688L12 16.9344L11.6123 17.1688L7.24805 19.8016C7.02019 19.9388 6.73888 19.7347 6.79883 19.4755L7.94727 14.5106L8.0498 14.0712L7.70801 13.7753L3.85547 10.4344C3.65456 10.2602 3.76146 9.93032 4.02637 9.9071L9.12109 9.46472L9.57129 9.42566L9.74707 9.00964L11.7227 4.33582Z"
        stroke="currentColor"
        strokeWidth="1.5"
      />
    </svg>
  )
}

export default FavoriteOutlineIcon
