/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function FavoriteFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="star"
        d="M7.63562 20.4435C6.8403 20.9233 5.85911 20.2114 6.06843 19.3065L7.21687 14.3417L3.36406 11.0014C2.66233 10.393 3.03652 9.24015 3.96178 9.15983L9.05654 8.71758L11.0317 4.04421C11.3935 3.18823 12.6065 3.18822 12.9683 4.04421L14.9435 8.71758L20.0382 9.15983C20.9635 9.24015 21.3377 10.393 20.6359 11.0014L16.7831 14.3417L17.9316 19.3065C18.1409 20.2114 17.1597 20.9233 16.3644 20.4435L12 17.8108L7.63562 20.4435Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default FavoriteFillIcon
