/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function FavoriteFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="star"
        d="M7.15069 21.3817C6.267 21.9148 5.17678 21.1238 5.40937 20.1183L6.68541 14.6019L2.40451 10.8905C1.62481 10.2145 2.04057 8.93349 3.06864 8.84424L8.72949 8.35285L10.9241 3.16022C11.3261 2.20913 12.6739 2.20912 13.0759 3.16022L15.2705 8.35285L20.9314 8.84424C21.9594 8.93349 22.3752 10.2145 21.5955 10.8905L17.3146 14.6019L18.5906 20.1183C18.8232 21.1238 17.733 21.9148 16.8493 21.3817L12 18.4564L7.15069 21.3817Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default FavoriteFillIcon
