/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HateOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 96 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.79921 6.57894C8.14104 6.57894 7.5519 6.98721 7.3208 7.60348L5.62921 12.1143C5.59597 12.203 5.57895 12.2969 5.57895 12.3915V12.8947C5.57895 13.3307 5.93241 13.6842 6.36842 13.6842H10.3158C10.5653 13.6842 10.8002 13.8022 10.9492 14.0024C11.0981 14.2026 11.1437 14.4615 11.072 14.7005L10.5773 16.3493C10.337 17.1503 10.7631 17.9911 11.5322 18.2803L13.5862 14.8569C13.7289 14.6191 13.9858 14.4736 14.2632 14.4736H17.4211V6.57894H8.79921ZM5.84238 7.04907C6.30458 5.81654 7.48286 5 8.79921 5H18.2105C18.6465 5 19 5.35346 19 5.78947V15.2631C19 15.6991 18.6465 16.0526 18.2105 16.0526H14.7101L12.5717 19.6166C12.3879 19.923 12.0213 20.0677 11.6779 19.9696L11.2221 19.8394C9.52957 19.3558 8.55915 17.5816 9.06497 15.8956L9.25471 15.2631H6.36842C5.06038 15.2631 4 14.2027 4 12.8947V12.3915C4 12.1075 4.05108 11.8259 4.1508 11.5599L5.84238 7.04907Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default HateOutlineIcon
