/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HateFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 96 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.84238 7.04907C6.30458 5.81654 7.48286 5 8.79921 5H18.2105C18.6465 5 19 5.35346 19 5.78947V15.2631C19 15.6991 18.6465 16.0526 18.2105 16.0526H14.7101L12.5717 19.6166C12.3879 19.923 12.0213 20.0677 11.6779 19.9696L11.2221 19.8394C9.52957 19.3558 8.55915 17.5816 9.06497 15.8956L9.25471 15.2631H6.36842C5.06038 15.2631 4 14.2027 4 12.8947V12.3915C4 12.1075 4.05108 11.8259 4.1508 11.5599L5.84238 7.04907Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default HateFillIcon
