/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HomeOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Rectangle 338 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M18 9.97007L12 5.40669L6 9.97007V19.0968H18V9.97007ZM4.4 8.65176C4.14819 8.84327 4 9.14384 4 9.46303V20.1109C4 20.671 4.44772 21.125 5 21.125H19C19.5523 21.125 20 20.671 20 20.1109V9.46303C20 9.14384 19.8518 8.84327 19.6 8.65176L12.6 3.32782C12.2444 3.05739 11.7556 3.05739 11.4 3.32782L4.4 8.65176Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default HomeOutlineIcon
