/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function HomeFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 8 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.5953 3.13234C11.8402 2.95589 12.1598 2.95589 12.4047 3.13234L19.6774 8.37315C19.879 8.51843 20 8.76233 20 9.02342V20.2174C20 20.6496 19.6744 21 19.2727 21H4.72727C4.32561 21 4 20.6496 4 20.2174V9.02342C4 8.76233 4.121 8.51843 4.3226 8.37315L11.5953 3.13234Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default HomeFillIcon
