/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function HomeOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path id="Rectangle 338" d="M5 9.5L12 4.25L19 9.5V20H5V9.5Z" stroke={color} strokeWidth="2" />
    </svg>
  )
}

export default HomeOutlineIcon
