/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function LikeFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector 96 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.4283 4.38336C11.6121 4.07705 11.9787 3.93231 12.3221 4.03045L12.7779 4.16065C14.4704 4.64424 15.4408 6.41838 14.935 8.10443L14.7453 8.73689H17.6316C18.9396 8.73689 20 9.79726 20 11.1053V11.6085C20 11.8925 19.9489 12.1741 19.8492 12.4401L18.1576 16.9509C17.6954 18.1835 16.5171 19 15.2008 19H5.78947C5.35346 19 5 18.6465 5 18.2105V8.73689C5 8.30088 5.35346 7.94742 5.78947 7.94742H9.28985L11.4283 4.38336Z"
        fill={color}
      />
    </svg>
  )
}

export default LikeFillIcon
