/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function LikeOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector 96 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.4283 4.38336C11.6121 4.07705 11.9787 3.93231 12.3221 4.03045L12.7779 4.16065C14.4704 4.64424 15.4408 6.41838 14.935 8.10443L14.7453 8.73689H17.6316C18.9396 8.73689 20 9.79726 20 11.1053V11.6085C20 11.8925 19.9489 12.1741 19.8492 12.4401L18.1576 16.9509C17.6954 18.1835 16.5171 19 15.2008 19H5.78947C5.35346 19 5 18.6465 5 18.2105V8.73689C5 8.30088 5.35346 7.94742 5.78947 7.94742H9.28985L11.4283 4.38336ZM12.4678 5.7197L10.4138 9.14307C10.2711 9.38086 10.0142 9.52636 9.73684 9.52636H6.57895V17.4211H15.2008C15.859 17.4211 16.4481 17.0128 16.6792 16.3965L18.3708 11.8857C18.404 11.797 18.4211 11.7031 18.4211 11.6085V11.1053C18.4211 10.6693 18.0676 10.3158 17.6316 10.3158H13.6842C13.4347 10.3158 13.1998 10.1978 13.0508 9.99762C12.9019 9.7974 12.8563 9.53854 12.928 9.29951L13.4227 7.65073C13.663 6.8497 13.2369 6.00892 12.4678 5.7197Z"
        fill={color}
      />
    </svg>
  )
}

export default LikeOutlineIcon
