/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function LinkedinFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector"
        d="M18.8571 4C19.4643 4 20 4.5357 20 5.17859V18.8571C20 19.5 19.4643 20 18.8571 20H5.10712C4.49996 20 4 19.5 4 18.8571V5.17859C4 4.5357 4.49996 4 5.10712 4H18.8571ZM8.82141 17.7143V10.1071H6.4643V17.7143H8.82141ZM7.64282 9.03573C8.39284 9.03573 9 8.42857 9 7.67855C9 6.92861 8.39284 6.28571 7.64282 6.28571C6.85714 6.28571 6.24998 6.92861 6.24998 7.67855C6.24998 8.42857 6.85714 9.03573 7.64282 9.03573ZM17.7143 17.7143V13.5357C17.7143 11.5 17.25 9.89288 14.8571 9.89288C13.7143 9.89288 12.9286 10.5357 12.6072 11.1429H12.5714V10.1071H10.3214V17.7143H12.6786V13.9643C12.6786 12.9643 12.8571 12 14.1071 12C15.3214 12 15.3214 13.1429 15.3214 14V17.7143H17.7143Z"
        fill={color}
      />
    </svg>
  )
}

export default LinkedinFillIcon
