/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function LockOffOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 3C10.148 3 8.53254 4.00738 7.66952 5.49927L9.40073 6.50073C9.92096 5.60141 10.8908 5 12 5C13.6569 5 15 6.34315 15 8V9H6.75C5.687 9 5 9.92252 5 10.8333V19.1667C5 20.0775 5.687 21 6.75 21H17.25C18.313 21 19 20.0775 19 19.1667V10.8333C19 9.92252 18.313 9 17.25 9H17V8C17 5.23858 14.7614 3 12 3ZM7 11V19H17V11H7Z"
        fill="currentColor"
      />
      <path
        d="M13.5 15C13.5 15.8284 12.8284 16.5 12 16.5C11.1716 16.5 10.5 15.8284 10.5 15C10.5 14.1716 11.1716 13.5 12 13.5C12.8284 13.5 13.5 14.1716 13.5 15Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default LockOffOutlineIcon
