/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function LoveitOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="favorite"
        d="M12 19L10.84 18.0082C9.49333 16.851 8.38 15.8529 7.5 15.0136C6.62 14.1744 5.92 13.421 5.4 12.7534C4.88 12.0858 4.51667 11.4723 4.31 10.9128C4.10333 10.3533 4 9.78111 4 9.19619C4 8.00091 4.42 7.00272 5.26 6.20163C6.1 5.40054 7.14667 5 8.4 5C9.09333 5 9.75333 5.13987 10.38 5.41962C11.0067 5.69936 11.5467 6.09355 12 6.60218C12.4533 6.09355 12.9933 5.69936 13.62 5.41962C14.2467 5.13987 14.9067 5 15.6 5C16.8533 5 17.9 5.40054 18.74 6.20163C19.58 7.00272 20 8.00091 20 9.19619C20 9.78111 19.8967 10.3533 19.69 10.9128C19.4833 11.4723 19.12 12.0858 18.6 12.7534C18.08 13.421 17.38 14.1744 16.5 15.0136C15.62 15.8529 14.5067 16.851 13.16 18.0082L12 19Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default LoveitOutlineIcon
