/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function MakerOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3 7C3 5.89543 3.89543 5 5 5H19C20.1046 5 21 5.89543 21 7V17C21 18.1046 20.1046 19 19 19H5C3.89543 19 3 18.1046 3 17V7ZM6.75 7H5V17H19V7H16.5L17 9H14.75L14.25 7H12.75L13.25 9H11L10.5 7H9L9.5 9H7.25L6.75 7ZM10 10.4099V14.5799C10 14.9099 10.38 15.1099 10.67 14.9199L13.82 12.8299C14.07 12.6699 14.07 12.3099 13.82 12.1499L10.67 10.0599C10.39 9.86995 10 10.0599 10 10.3999V10.4099Z"
        fill={color}
      />
    </svg>
  )
}

export default MakerOutlineIcon
