/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ManagerCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.0001 7.5C11.4907 7.5 11.0778 7.91767 11.0778 8.43289C11.0778 8.6498 11.1511 8.84956 11.2738 9.00797L9.92196 10.8528L8.21616 10.201C8.17523 9.72407 7.77949 9.34986 7.29732 9.34986C6.78794 9.34986 6.375 9.76753 6.375 10.2827C6.375 10.7249 6.67901 11.095 7.08719 11.1913L7.94222 15.083V16.0956C7.94222 16.319 8.12122 16.5 8.34203 16.5H15.6573C15.8781 16.5 16.0571 16.319 16.0571 16.0956V15.083L16.9121 11.1914C17.3207 11.0955 17.625 10.7251 17.625 10.2827C17.625 9.76753 17.2121 9.34986 16.7027 9.34986C16.2206 9.34986 15.8249 9.72394 15.7839 10.2008L14.0774 10.8528L12.7259 9.00854C12.8489 8.85004 12.9224 8.65006 12.9224 8.43289C12.9224 7.91767 12.5095 7.5 12.0001 7.5ZM8.66274 14.6342H15.3366L16.1317 11.0154C16.1088 10.9972 16.0869 10.9779 16.0658 10.9576L14.0774 11.7174C13.9102 11.7813 13.7213 11.7251 13.6149 11.5799L11.9997 9.37568L10.3845 11.5799C10.278 11.7251 10.0892 11.7813 9.92198 11.7174L7.93397 10.9577C7.91283 10.9781 7.89074 10.9975 7.86776 11.0159L8.66274 14.6342Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ManagerCircleOutlineIcon
