/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function MeCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M6.24451 8.79376H7.5778L9.49776 13.4973L11.4177 8.79376H12.751V15.2063H11.6287V11.0527L9.94526 15.1977H9.05034L7.36687 11.0641V15.2063H6.24451V8.79376Z"
        fill="currentColor"
      />
      <path
        d="M14.7814 9.83066V11.4773H17.5162V12.5056H14.7814V14.1694H17.7555V15.2063H13.6163V8.79376H17.7213V9.83066H14.7814Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM19.5 12C19.5 16.1421 16.1421 19.5 12 19.5C7.85786 19.5 4.5 16.1421 4.5 12C4.5 7.85786 7.85786 4.5 12 4.5C16.1421 4.5 19.5 7.85786 19.5 12Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default MeCircleOutlineIcon
