/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function MeCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.70829 8.51239H6.375V14.9249H7.49736V10.7827L9.18084 14.9163H10.0758L11.7592 10.7714V14.9249H12.8815V8.51239H11.5482L9.62825 13.2159L7.70829 8.51239ZM14.9119 11.1959V9.54929H17.8518V8.51239H13.7468V14.9249H17.886V13.888H14.9119V12.2243H17.6467V11.1959H14.9119Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default MeCircleOutlineIcon
