/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function MinusCircleOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <circle id="Ellipse 75" cx="12" cy="12" r="8.25" stroke={color} strokeWidth="1.5" />
      <path id="Vector 48" d="M8 12H16" stroke={color} strokeWidth="1.28571" strokeLinecap="round" />
    </svg>
  )
}

export default MinusCircleOutlineIcon
