/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ModelFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5 8C4.44772 8 4 8.44772 4 9C4 9.55228 4.44772 10 5 10H9V12V15V20C9 20.5523 9.44772 21 10 21C10.5523 21 11 20.5523 11 20V15H13V20C13 20.5523 13.4477 21 14 21C14.5523 21 15 20.5523 15 20V15V12V10H19C19.5523 10 20 9.55228 20 9C20 8.44772 19.5523 8 19 8H15H9H5Z"
        fill={color}
      />
      <path
        id="Vector"
        d="M12 6C12.5523 6 13 5.55228 13 5C13 4.44772 12.5523 4 12 4C11.4477 4 11 4.44772 11 5C11 5.55228 11.4477 6 12 6Z"
        fill={color}
        stroke={color}
        strokeWidth="2"
        strokeMiterlimit="10"
        strokeLinecap="round"
      />
    </svg>
  )
}

export default ModelFillIcon
