/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ModelFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10 5C10 3.89543 10.8954 3 12 3C13.1046 3 14 3.89543 14 5C14 6.10457 13.1046 7 12 7C10.8954 7 10 6.10457 10 5ZM4 9C4 8.44772 4.44772 8 5 8H9H15H19C19.5523 8 20 8.44772 20 9C20 9.55228 19.5523 10 19 10H15V12V15V20C15 20.5523 14.5523 21 14 21C13.4477 21 13 20.5523 13 20V15H11V20C11 20.5523 10.5523 21 10 21C9.44772 21 9 20.5523 9 20V15V12V10H5C4.44772 10 4 9.55228 4 9Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ModelFillIcon
