/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function MotionFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M14 7C15.1046 7 16 6.10457 16 5C16 3.89543 15.1046 3 14 3C12.8954 3 12 3.89543 12 5C12 6.10457 12.8954 7 14 7Z"
        fill="currentColor"
      />
      <path
        d="M10.0334 12.7436L10.7054 10.0558L9 10.7244V12C9 12.5523 8.55228 13 8 13C7.44772 13 7 12.5523 7 12V10.0424C7 9.63099 7.25196 9.26157 7.63498 9.11139L11.2035 7.71229C12.4528 7.21827 13.8875 7.60666 14.7028 8.66943L14.7038 8.67071L16.1049 10.4883L17.3005 9.31797C17.6952 8.93165 18.3283 8.93843 18.7146 9.33312C19.101 9.7278 19.0942 10.3609 18.6995 10.7472L16.6995 12.7049C16.4953 12.9047 16.2154 13.0077 15.9304 12.9878C15.6453 12.9679 15.3824 12.827 15.208 12.6007L14.5833 11.7903L14.1075 13.6933L15.7071 15.2929C15.8946 15.4804 16 15.7348 16 16V20C16 20.5523 15.5523 21 15 21C14.4477 21 14 20.5523 14 20V16.4142L12.4076 14.8219L11.6678 14.4519L10.9701 17.2425C10.8589 17.6877 10.4589 18 10 18H7C6.44772 18 6 17.5523 6 17C6 16.4477 6.44772 16 7 16H9.21922L10.0299 12.7575C10.031 12.7528 10.0322 12.7482 10.0334 12.7436Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default MotionFillIcon
