/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function MyAssetOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4 7.51961C4 8.26161 4.40681 8.89493 5 9.23438V17.953C5 19.0506 5.85985 20 7 20H17C18.1463 20 19 19.0341 19 17.953V9.23438C19.5932 8.89493 20 8.26161 20 7.51961V5.98039C20 4.86808 19.0858 4 18 4H6C4.91419 4 4 4.86808 4 5.98039V7.51961ZM7 17.953V9.5H17V17.953C17 17.9748 16.9922 17.9907 16.984 18H7.01263C7.01054 17.9972 7.00809 17.9933 7.00592 17.9879C7.00306 17.9808 7 17.9697 7 17.953ZM6 6V7.5H18V6H6ZM10 12C9.44772 12 9 12.4477 9 13C9 13.5523 9.44772 14 10 14H14C14.5523 14 15 13.5523 15 13C15 12.4477 14.5523 12 14 12H10Z"
        fill={color}
      />
    </svg>
  )
}

export default MyAssetOutlineIcon
