/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function MyCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 11"
        d="M6.68188 14.2314V9.54547H7.03891L9.35958 14.0362L11.6802 9.54547H12.0373V14.2314"
        stroke="currentColor"
        strokeWidth="1.22728"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        id="Vector 12"
        d="M14.0455 10.2148L16.1595 14.9194M16.1595 14.9194L18.0621 10.2148M16.1595 14.9194C15.5779 16.1499 14.8326 16.4058 14.0873 16.1499"
        stroke="currentColor"
        strokeWidth="1.22728"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default MyCircleOutlineIcon
