/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function NotificationFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.5382 3.85712C8.53879 3.85712 6.10728 6.28857 6.10722 9.28795L6.10719 10.6784C6.10718 10.9866 5.98676 11.2826 5.77161 11.5033C4.88763 12.4099 4.39288 13.6261 4.39288 14.8923V15.8479C4.39288 16.6814 5.06859 17.3571 5.90211 17.3571L8.72156 17.3571C8.9777 18.9368 10.348 20.1428 12 20.1428C13.652 20.1428 15.0223 18.9368 15.2785 17.3571L18.098 17.3571C18.9315 17.3571 19.6072 16.6814 19.6072 15.8479V14.8924C19.6072 13.6261 19.1124 12.4099 18.2283 11.5033C18.0132 11.2826 17.8927 10.9866 17.8928 10.6784L17.8928 9.28787C17.8928 6.28857 15.4614 3.85712 12.4621 3.85712H11.5382ZM13.7414 17.3571L10.2586 17.3571C10.4874 18.1016 11.1805 18.6428 12 18.6428C12.8195 18.6428 13.5126 18.1016 13.7414 17.3571Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default NotificationFillIcon
