/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function PauseOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="pause (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.5 6.5V17.5H9.5V6.5H7.5ZM14.5 6.5V17.5H16.5V6.5H14.5ZM7 5C6.44772 5 6 5.44772 6 6V18C6 18.5523 6.44772 19 7 19H10C10.5523 19 11 18.5523 11 18V6C11 5.44772 10.5523 5 10 5H7ZM14 5C13.4477 5 13 5.44772 13 6V18C13 18.5523 13.4477 19 14 19H17C17.5523 19 18 18.5523 18 18V6C18 5.44772 17.5523 5 17 5H14Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default PauseOutlineIcon
