/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function PauseCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector"
        d="M12 4.63636C11.033 4.63636 10.0755 4.82683 9.18206 5.19689C8.28866 5.56694 7.4769 6.10935 6.79312 6.79312C6.10935 7.4769 5.56694 8.28866 5.19689 9.18206C4.82683 10.0755 4.63636 11.033 4.63636 12C4.63636 12.967 4.82683 13.9245 5.19689 14.8179C5.56694 15.7113 6.10935 16.5231 6.79312 17.2069C7.4769 17.8907 8.28866 18.4331 9.18206 18.8031C10.0755 19.1732 11.033 19.3636 12 19.3636C13.953 19.3636 15.8259 18.5878 17.2069 17.2069C18.5878 15.8259 19.3636 13.953 19.3636 12C19.3636 10.047 18.5878 8.17407 17.2069 6.79312C15.8259 5.41217 13.953 4.63636 12 4.63636ZM3 12C3 7.02955 7.02955 3 12 3C16.9705 3 21 7.02955 21 12C21 16.9705 16.9705 21 12 21C7.02955 21 3 16.9705 3 12ZM10.7727 7.90909V16.0909H9.13636V7.90909H10.7727ZM14.8636 7.90909V16.0909H13.2273V7.90909H14.8636Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default PauseCircleOutlineIcon
