/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function PauseOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="pause"
        d="M6.75 6C6.75 5.86193 6.86193 5.75 7 5.75H10C10.1381 5.75 10.25 5.86193 10.25 6V18C10.25 18.1381 10.1381 18.25 10 18.25H7C6.86193 18.25 6.75 18.1381 6.75 18V6ZM13.75 6C13.75 5.86193 13.8619 5.75 14 5.75H17C17.1381 5.75 17.25 5.86193 17.25 6V18C17.25 18.1381 17.1381 18.25 17 18.25H14C13.8619 18.25 13.75 18.1381 13.75 18V6Z"
        stroke={color}
        strokeWidth="1.5"
      />
    </svg>
  )
}

export default PauseOutlineIcon
