/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function PlayOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="play (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.9575 12L7.5 6.0741V17.9259L17.9575 12ZM8.23952 4.76907L18.697 10.695C19.711 11.2696 19.711 12.7305 18.697 13.305L8.23952 19.2309C7.23957 19.7976 6 19.0753 6 17.9259V6.0741C6 4.92476 7.23957 4.20243 8.23952 4.76907Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default PlayOutlineIcon
