/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function PlayOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="play"
        d="M7.86976 5.42158L18.3272 11.3475C18.8342 11.6348 18.8342 12.3652 18.3272 12.6525L7.86976 18.5784C7.36978 18.8617 6.75 18.5006 6.75 17.9259V6.07409C6.75 5.49942 7.36978 5.13826 7.86976 5.42158Z"
        stroke={color}
        strokeWidth="1.5"
      />
    </svg>
  )
}

export default PlayOutlineIcon
