/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function PlayFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="play"
        d="M18.697 10.695L8.23952 4.76906C7.23957 4.20242 6 4.92475 6 6.07409V17.9259C6 19.0752 7.23957 19.7976 8.23952 19.2309L18.697 13.305C19.711 12.7304 19.711 11.2696 18.697 10.695Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default PlayFillIcon
