/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function QuestionOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector"
        d="M12 19C12.6904 19 13.25 18.4404 13.25 17.75C13.25 17.0596 12.6904 16.5 12 16.5C11.3096 16.5 10.75 17.0596 10.75 17.75C10.75 18.4404 11.3096 19 12 19Z"
        fill={color}
      />
      <path
        id="Vector2"
        d="M12 14.49V13.07C12 12.52 12.16 12.35 12.62 11.92C13.22 11.35 13.9 10.76 14.41 10.21C15.59 8.95001 15.5 7.06001 14.2 5.89001C13.36 5.14001 12.21 4.86001 11.13 5.05001C11 5.07001 10.84 5.12001 10.66 5.18001C9.17999 5.69001 8.23999 7.01001 8.23999 8.46001V8.65001"
        stroke={color}
        strokeWidth="2"
        strokeMiterlimit="10"
        strokeLinecap="round"
      />
    </svg>
  )
}

export default QuestionOutlineIcon
