/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ReportOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 41 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.9017 6.51377C12.2385 5.72229 11.1548 5.42335 10.1794 5.76286L7.625 6.65206V12.7276L10.1833 11.9055C11.7484 11.4026 13.4621 11.8976 14.5177 13.1575C15.2193 13.9948 16.391 14.2535 17.375 13.8029V7.76581C15.7816 8.30801 13.9992 7.82363 12.9017 6.51377ZM7.625 14.4339L10.6806 13.4521C11.6163 13.1514 12.6409 13.4474 13.272 14.2006C14.4908 15.6553 16.5582 16.0658 18.2407 15.1873L18.5637 15.0187C18.8319 14.8786 19 14.6012 19 14.2987V6.5317C19 6.25635 18.8605 5.99976 18.6293 5.85003C18.3982 5.70031 18.1069 5.67784 17.8555 5.79035L17.0679 6.14286C16.0536 6.59683 14.861 6.32234 14.1474 5.47065C13.0506 4.1616 11.2582 3.66718 9.64506 4.22871L6.54531 5.30774C6.2188 5.4214 6 5.72918 6 6.07481V18.8678C6 19.3163 6.36377 19.68 6.8125 19.68C7.26123 19.68 7.625 19.3163 7.625 18.8678V14.4339Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ReportOutlineIcon
