/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ReportOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector 41"
        d="M5 21V14.8123M5 14.8123V5.24997L8.81507 3.92152C10.408 3.36686 12.1779 3.85523 13.261 5.14827V5.14827C14.4264 6.53967 16.374 6.98809 18.0306 6.24644L19 5.81246V15.3748L18.6025 15.5825C16.9481 16.4466 14.9152 16.0427 13.7167 14.6119V14.6119C12.6788 13.3727 10.9936 12.8858 9.45471 13.3805L5 14.8123Z"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default ReportOutlineIcon
