/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ReportFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.6806 13.455L7.625 14.4372V18.8724C7.625 19.3211 7.26123 19.6849 6.8125 19.6849C6.36377 19.6849 6 19.3211 6 18.8724V6.07546C6 5.72971 6.2188 5.42184 6.54531 5.30814L9.64506 4.22878C11.2582 3.66708 13.0506 4.16165 14.1474 5.4711C14.861 6.32306 16.0536 6.59763 17.0679 6.14352L17.8555 5.79091C18.1069 5.67836 18.3982 5.70083 18.6293 5.8506C18.8605 6.00038 19 6.25705 19 6.53248V14.3019C19 14.6045 18.8319 14.882 18.5637 15.0221L18.2407 15.1908C16.5582 16.0696 14.4908 15.6589 13.272 14.2038C12.6409 13.4503 11.6163 13.1543 10.6806 13.455Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ReportFillIcon
