/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ReportOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Vector 41 (Stroke)"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.4944 5.01224C11.6782 3.97385 10.3443 3.58166 9.14391 4.02709L6 5.19368V13.1645L9.1487 12.086C11.0749 11.4262 13.1842 12.0756 14.4833 13.7285C15.3468 14.827 16.789 15.1664 18 14.5752V6.65486C16.0388 7.36621 13.8451 6.73071 12.4944 5.01224ZM6 15.4031L9.76071 14.115C10.9123 13.7205 12.1734 14.1088 12.9501 15.097C14.4503 17.0055 16.9947 17.5441 19.0654 16.3915L19.463 16.1703C19.7931 15.9865 20 15.6226 20 15.2257V5.03576C20 4.67452 19.8283 4.33788 19.5438 4.14145C19.2593 3.94502 18.9008 3.91554 18.5914 4.06315L17.622 4.52562C16.3736 5.12121 14.9059 4.7611 14.0276 3.64371C12.6776 1.92631 10.4716 1.27766 8.48623 2.01436L4.67116 3.42999C4.26929 3.5791 4 3.98289 4 4.43635V21.2201C4 21.8086 4.44772 22.2857 5 22.2857C5.55228 22.2857 6 21.8086 6 21.2201V15.4031Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ReportOutlineIcon
