/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ReportFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.76071 13.9847L6 15.1935V20.6522C6 21.2045 5.55228 21.6522 5 21.6522C4.44772 21.6522 4 21.2045 4 20.6522V4.90218C4 4.47665 4.26929 4.09773 4.67116 3.9578L8.48623 2.62936C10.4716 1.93803 12.6776 2.54673 14.0276 4.15836C14.9059 5.20693 16.3736 5.54487 17.622 4.98596L18.5914 4.55197C18.9008 4.41345 19.2593 4.44111 19.5438 4.62545C19.8283 4.80978 20 5.12569 20 5.46468V15.027C20 15.3994 19.7931 15.741 19.463 15.9134L19.0654 16.121C16.9947 17.2026 14.4503 16.6972 12.9501 14.9062C12.1734 13.9789 10.9123 13.6146 9.76071 13.9847Z"
        fill={color}
      />
    </svg>
  )
}

export default ReportFillIcon
