/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SaveCloudOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        d="M14.7396 12.3003C15.0435 12.0189 15.0617 11.5444 14.7803 11.2404C14.4989 10.9365 14.0244 10.9183 13.7204 11.1997L11.5305 13.2274L10.2401 12.0302C9.93645 11.7485 9.46191 11.7662 9.18018 12.0699C8.89846 12.3735 8.91624 12.8481 9.21989 13.1298L11.0199 14.7998C11.3074 15.0665 11.7518 15.0668 12.0396 14.8003L14.7396 12.3003Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 5C9.30157 5 6.84661 6.85362 6.40596 9.59274C4.43766 10.0778 3 12.0609 3 14.23C3 16.7211 4.92077 19 7.31586 19H17.1036C19.3559 19 21 16.9244 21 14.83C21 12.9158 19.6314 11.0477 17.6927 10.728C17.6222 7.56491 15.0259 5 12 5ZM8.33583 10.48C8.33583 8.49843 9.98685 7 12 7C13.9259 7 15.6941 8.70342 15.6941 10.86V12.68H17.1036C18.0549 12.68 19 13.6329 19 14.83C19 16.0356 18.0473 17 17.1036 17H7.31586C6.23528 17 5 15.8389 5 14.23C5 12.6283 6.20885 11.48 7.33583 11.48H8.33583V10.48Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default SaveCloudOutlineIcon
