/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function SaveOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="save"
        d="M21 7V19C21 19.55 20.8042 20.0208 20.4125 20.4125C20.0208 20.8042 19.55 21 19 21H5C4.45 21 3.97917 20.8042 3.5875 20.4125C3.19583 20.0208 3 19.55 3 19V5C3 4.45 3.19583 3.97917 3.5875 3.5875C3.97917 3.19583 4.45 3 5 3H17L21 7ZM19 7.85L16.15 5H5V19H19V7.85ZM12 17C12.8333 17 13.5417 16.7083 14.125 16.125C14.7083 15.5417 15 14.8333 15 14C15 13.1667 14.7083 12.4583 14.125 11.875C13.5417 11.2917 12.8333 11 12 11C11.1667 11 10.4583 11.2917 9.875 11.875C9.29167 12.4583 9 13.1667 9 14C9 14.8333 9.29167 15.5417 9.875 16.125C10.4583 16.7083 11.1667 17 12 17ZM6 7C6 7.55228 6.44772 8 7 8H12C12.5523 8 13 7.55228 13 7C13 6.44772 12.5523 6 12 6H7C6.44772 6 6 6.44772 6 7Z"
        fill={color}
      />
    </svg>
  )
}

export default SaveOutlineIcon
