/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ScaleIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        d="M19.9999 5.01538C20.0039 4.75436 19.9063 4.49207 19.7071 4.29289C19.5982 4.184 19.4705 4.10548 19.3344 4.05731C19.2317 4.02098 19.1243 4.00192 19.0167 4.00014C19.0111 4.00005 19.0055 4 18.9999 4C18.9999 4 18.9999 4 18.9999 4H14.6299C14.0776 4 13.6299 4.44772 13.6299 5C13.6299 5.55228 14.0776 6 14.6299 6H16.5858L6 16.5858V14.6201C6 14.0678 5.55228 13.6201 5 13.6201C4.44772 13.6201 4 14.0678 4 14.6201V18.9998C4 19.1607 4.03799 19.313 4.10549 19.4477C4.13105 19.4987 4.16124 19.548 4.19608 19.595C4.37827 19.8408 4.67053 20.0001 5 20.0001H9.38C9.93228 20.0001 10.38 19.5524 10.38 19.0001C10.38 18.4478 9.93228 18.0001 9.38 18.0001H7.4141L17.9999 7.41433V9.38C17.9999 9.93228 18.4476 10.38 18.9999 10.38C19.5522 10.38 19.9999 9.93228 19.9999 9.38V5.01538Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ScaleIcon
