/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SearchFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10 3C6.13401 3 3 6.13401 3 10C3 13.866 6.13401 17 10 17C11.5759 17 13.0302 16.4792 14.2001 15.6004C14.2281 15.6376 14.259 15.6733 14.2929 15.7071L18.2929 19.7071C18.6834 20.0976 19.3166 20.0976 19.7071 19.7071C20.0976 19.3166 20.0976 18.6834 19.7071 18.2929L15.7071 14.2929C15.6733 14.259 15.6376 14.2281 15.6004 14.2001C16.4792 13.0302 17 11.5759 17 10C17 6.13401 13.866 3 10 3Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default SearchFillIcon
