/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function SendFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Subtract"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.6888 20.2389C13.1346 21.0164 14.2623 20.9544 14.5378 20.1372L19.1764 6.37715C19.4478 5.57205 18.6411 4.76542 17.836 5.03683L4.07601 9.67538C3.25883 9.95085 3.1968 11.0786 3.97431 11.5244L7.97866 13.8201C8.33884 14.0266 8.77621 14.006 9.09242 13.7677L13.3931 10.5265C13.5786 10.3866 13.8266 10.6346 13.6867 10.8202L10.4455 15.1208C10.2072 15.437 10.1866 15.8744 10.3931 16.2345L12.6888 20.2389Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default SendFillIcon
