/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function SetToCenterOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M13 4C13 3.44772 12.5523 3 12 3C11.4477 3 11 3.44772 11 4V5.07089C7.93431 5.5094 5.5094 7.93431 5.07089 11H4C3.44772 11 3 11.4477 3 12C3 12.5523 3.44772 13 4 13H5.07089C5.5094 16.0657 7.93431 18.4906 11 18.9291V20C11 20.5523 11.4477 21 12 21C12.5523 21 13 20.5523 13 20V18.9291C16.0657 18.4906 18.4906 16.0657 18.9291 13H20C20.5523 13 21 12.5523 21 12C21 11.4477 20.5523 11 20 11H18.9291C18.4906 7.93431 16.0657 5.5094 13 5.07089V4ZM12 17C9.23858 17 7 14.7614 7 12C7 9.23858 9.23858 7 12 7C14.7614 7 17 9.23858 17 12C17 14.7614 14.7614 17 12 17ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z"
        fill={color}
      />
    </svg>
  )
}

export default SetToCenterOutlineIcon
