/**
 * DO NOT EDIT - automatically generated by script
 */

import * as React from 'react'

type Props = React.SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function UndoOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.20711 5.70711C9.59763 5.31658 9.59763 4.68342 9.20711 4.29289C8.81658 3.90237 8.18342 3.90237 7.79289 4.29289L4.29289 7.79289C3.90237 8.18342 3.90237 8.81658 4.29289 9.20711L7.79289 12.7071C8.18342 13.0976 8.81658 13.0976 9.20711 12.7071C9.59763 12.3166 9.59763 11.6834 9.20711 11.2929L7.41421 9.5H13.75C16.0977 9.5 18 11.4023 18 13.75C18 16.0977 16.0977 18 13.75 18H5C4.44772 18 4 18.4477 4 19C4 19.5523 4.44772 20 5 20H13.75C17.2023 20 20 17.2023 20 13.75C20 10.2977 17.2023 7.5 13.75 7.5H7.41421L9.20711 5.70711Z"
        fill={color}
      />
    </svg>
  )
}

export default UndoOutlineIcon
