/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function UserFillIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Vector"
        d="M12 10.9999C13.6569 10.9999 15 9.65679 15 7.99994C15 6.34308 13.6569 4.99994 12 4.99994C10.3431 4.99994 9 6.34308 9 7.99994C9 9.65679 10.3431 10.9999 12 10.9999Z"
        fill={color}
        stroke={color}
        strokeWidth="1.5"
        strokeMiterlimit="10"
        strokeLinecap="round"
      />
      <path
        id="Vector2"
        d="M5.00055 18.5621C5.00055 18.8009 5.20084 18.9999 5.46121 18.9999H12H18.5399C18.7903 18.9999 19.0006 18.8009 19.0006 18.5621V18.3532C19.0006 17.2089 18.3797 16.1442 17.3582 15.5373L17.1078 15.388C13.9834 13.5373 10.0177 13.5373 6.89325 15.388L6.6429 15.5373C5.62144 16.1442 5.00055 17.2089 5.00055 18.3532V18.5621Z"
        fill={color}
        stroke={color}
        strokeWidth="1.5"
        strokeMiterlimit="10"
        strokeLinecap="round"
      />
    </svg>
  )
}

export default UserFillIcon
