/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function UserFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.24945 8C8.24945 5.92893 9.92838 4.25 11.9995 4.25C14.0705 4.25 15.7495 5.92893 15.7495 8C15.7495 10.0711 14.0705 11.75 11.9995 11.75C9.92838 11.75 8.24945 10.0711 8.24945 8ZM6.51047 14.7428C9.87063 12.7524 14.1294 12.7524 17.4895 14.7428L17.4914 14.7438L17.7408 14.8926C18.9786 15.6284 19.75 16.9325 19.75 18.3532V18.5622C19.75 19.2516 19.1665 19.75 18.5393 19.75H5.46066C4.81261 19.75 4.25 19.2413 4.25 18.5622V18.3532C4.25 16.9325 5.02065 15.6289 6.25849 14.893L6.50865 14.7439L6.51047 14.7428Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default UserFillIcon
