/**
 * DO NOT EDIT - automatically generated by script
 */

import { SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: string
}

function ZoomOutOutlineIcon({ size = 24, color = 'white', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10 5C7.23858 5 5 7.23858 5 10C5 12.7614 7.23858 15 10 15C12.7614 15 15 12.7614 15 10C15 7.23858 12.7614 5 10 5ZM3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10C17 11.5759 16.4792 13.0302 15.6004 14.2001C15.6376 14.2281 15.6733 14.259 15.7071 14.2929L19.7071 18.2929C20.0976 18.6834 20.0976 19.3166 19.7071 19.7071C19.3166 20.0976 18.6834 20.0976 18.2929 19.7071L14.2929 15.7071C14.259 15.6733 14.2281 15.6376 14.2001 15.6004C13.0302 16.4792 11.5759 17 10 17C6.13401 17 3 13.866 3 10ZM7.75 9.25C7.33579 9.25 7 9.58579 7 10C7 10.4142 7.33579 10.75 7.75 10.75H12.25C12.6642 10.75 13 10.4142 13 10C13 9.58579 12.6642 9.25 12.25 9.25H7.75Z"
        fill={color}
      />
    </svg>
  )
}

export default ZoomOutOutlineIcon
