/**
 * DO NOT EDIT - automatically generated by script
 */

import { CSSProperties, SVGProps } from 'react'

type Props = SVGProps<SVGSVGElement> & {
  size?: number
  color?: CSSProperties['color']
}

function ZoonInOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      strokeWidth="0"
      color={color}
      {...props}
    >
      <path
        id="Union"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5 10C5 7.23858 7.23858 5 10 5C12.7614 5 15 7.23858 15 10C15 12.7614 12.7614 15 10 15C7.23858 15 5 12.7614 5 10ZM10 3C6.13401 3 3 6.13401 3 10C3 13.866 6.13401 17 10 17C11.5759 17 13.0302 16.4792 14.2001 15.6004C14.2281 15.6376 14.259 15.6733 14.2929 15.7071L18.2929 19.7071C18.6834 20.0976 19.3166 20.0976 19.7071 19.7071C20.0976 19.3166 20.0976 18.6834 19.7071 18.2929L15.7071 14.2929C15.6733 14.259 15.6376 14.2281 15.6004 14.2001C16.4792 13.0302 17 11.5759 17 10C17 6.13401 13.866 3 10 3ZM10 7C10.4142 7 10.75 7.33579 10.75 7.75V9.25H12.25C12.6642 9.25 13 9.58579 13 10C13 10.4142 12.6642 10.75 12.25 10.75H10.75V12.25C10.75 12.6642 10.4142 13 10 13C9.58579 13 9.25 12.6642 9.25 12.25V10.75H7.75C7.33579 10.75 7 10.4142 7 10C7 9.58579 7.33579 9.25 7.75 9.25H9.25V7.75C9.25 7.33579 9.58579 7 10 7Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default ZoonInOutlineIcon
